/**
 * Build-time version stamp for the shipped bundles.
 *
 * `__VALIDITY_BUILD_STAMP__` is a free identifier replaced by a bundler's
 * `define` at build time with a `<gitShortSha>.<yyyymmddHHmm>` string. A
 * npm's tsc build instead reads the adjacent build-info.json generated by
 * build/prepack. Unstamped source runs fall back to dev; the typeof guard
 * keeps them from throwing a ReferenceError.
 */
import { readFileSync } from 'node:fs';

declare const __VALIDITY_BUILD_STAMP__: string | undefined;

/** The bundler-injected or packaged tsc stamp, or undefined in an unstamped build. */
export function getBuildStamp(): string | undefined {
  if (typeof __VALIDITY_BUILD_STAMP__ !== 'undefined') return __VALIDITY_BUILD_STAMP__;
  try {
    const { stamp } = JSON.parse(
      readFileSync(new URL('./build-info.json', import.meta.url), 'utf8'),
    );
    return typeof stamp === 'string' ? stamp : undefined;
  } catch {
    return undefined;
  }
}

/**
 * Human-facing version string: `<pkgVersion>+<stamp>` for a shipped build,
 * `<pkgVersion>+dev` when unstamped. Callers pass their own package.json
 * version so the CLI and MCP server each stamp their own identity.
 */
export function formatBuildVersion(pkgVersion: string): string {
  const stamp = getBuildStamp();
  return `${pkgVersion}+${stamp ?? 'dev'}`;
}
