/**
 * Unit tests for the Playwright scaffold exporter. We don't execute the
 * generated specs — that would pull Playwright + a real app into the
 * test loop and isn't what we're verifying. We assert that the SOURCE
 * the exporter emits contains the right shapes (page.route calls,
 * cookies, play-body inlining, criteria → test.step blocks, etc.).
 */
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { resolve } from 'node:path';
import { runInNewContext } from 'node:vm';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import type { RunMeta, ValidityConfig } from '@validity.ai/verify-spec';
import { exportPlaywright, loadReportCriteria } from './playwright.js';

function makeIsolationMeta(overrides?: Partial<RunMeta>): RunMeta {
  return {
    runId: 'run_test_1',
    createdAt: '2026-01-01T00:00:00.000Z',
    mode: 'isolation',
    prompt: 'Add a Sign in button that posts to /api/login',
    scenarios: ['logged-in'],
    components: [
      {
        id: 'src-components-login-form',
        filePath: 'src/components/LoginForm.tsx',
        screenshotPath: '/tmp/x.png',
        scenarioId: 'logged-in',
      },
    ],
    componentSources: { 'src-components-login-form': '// source' },
    diff: { files: [] },
    report: { enabled: true, brand: 'validity' },
    git: { sha: 'abcdef1234567890', branch: 'feat/login', dirty: false },
    ...overrides,
  };
}

function makeConfig(overrides?: Partial<ValidityConfig>): ValidityConfig {
  return {
    renderMode: 'web',
    framework: 'auto',
    wrapper: './.validity/wrapper.gen.tsx',
    mockNetwork: {
      cookies: { base_cookie: 'b' },
      handlers: [{ url: '/api/health', json: { ok: true } }],
    },
    scenarios: {
      'logged-in': {
        mockNetwork: {
          cookies: { session: 'mock-session' },
          localStorage: { token: 'abc' },
          handlers: [{ url: '/api/me', method: 'GET', json: { id: '1', name: 'Ada' } }],
        },
        play: async ({ page }) => {
          await (page as any).click('button[type=submit]');
          await (page as any).fill('input[name=email]', 'ada@example.com');
        },
      },
    },
    ...overrides,
  };
}

describe('exportPlaywright (isolation mode)', () => {
  let outDir: string;

  beforeEach(() => {
    outDir = mkdtempSync(resolve(tmpdir(), 'validity-export-test-'));
  });

  afterEach(() => {
    rmSync(outDir, { recursive: true, force: true });
  });

  it('writes one spec per (component × scenario) pair', () => {
    const result = exportPlaywright({
      runMeta: makeIsolationMeta(),
      config: makeConfig(),
      outDir,
    });
    expect(result.written).toHaveLength(1);
    expect(result.skipped).toEqual([]);
    const file = result.written[0]!;
    expect(file).toMatch(/src-components-login-form\.logged-in\.spec\.ts$/);
  });

  it('emits the scaffold header with run id and git info', () => {
    const result = exportPlaywright({
      runMeta: makeIsolationMeta(),
      config: makeConfig(),
      outDir,
    });
    const src = readFileSync(result.written[0]!, 'utf-8');
    expect(src).toContain('Generated by Validity. Edit freely.');
    expect(src).toContain('Source run: run_test_1');
    expect(src).toContain('git: feat/login @ abcdef1');
    expect(src).toContain('isolation');
    expect(src).toMatch(/TODO: this scaffold was produced for a component/);
  });

  it('translates mockNetwork handlers into page.route() calls', () => {
    const result = exportPlaywright({
      runMeta: makeIsolationMeta(),
      config: makeConfig(),
      outDir,
    });
    const src = readFileSync(result.written[0]!, 'utf-8');
    // Scenario handler wins on URL conflict (first in merged.handlers).
    expect(src).toContain('await page.route("**/api/me"');
    expect(src).toContain('await page.route("**/api/health"');
    expect(src).toContain('JSON.stringify({"id":"1","name":"Ada"})');
    // Method guard for the explicit GET handler.
    expect(src).toContain('route.request().method() !== "GET"');
  });

  it('seeds cookies via context.addCookies', () => {
    const result = exportPlaywright({
      runMeta: makeIsolationMeta(),
      config: makeConfig(),
      outDir,
      baseUrl: 'http://localhost:5173',
    });
    const src = readFileSync(result.written[0]!, 'utf-8');
    expect(src).toContain('await context.addCookies([');
    expect(src).toContain('name: "base_cookie"');
    expect(src).toContain('name: "session"');
    expect(src).toContain('value: "mock-session"');
    expect(src).toContain('url: "http://localhost:5173"');
  });

  it.each([undefined, 'http://localhost:5173/dashboard'])(
    'scopes exported storage seeds to the navigation origin (%s)',
    (baseUrl) => {
      const result = exportPlaywright({
        runMeta: makeIsolationMeta(),
        config: makeConfig({ mockNetwork: { sessionStorage: { seed: 'synthetic-session' } } }),
        outDir,
        baseUrl,
      });
      const src = readFileSync(result.written[0]!, 'utf-8');
      const script = src.match(
        /await context\.addInitScript\(\(\) => \{([\s\S]*?)\n    \}\);/,
      )?.[1];
      expect(script).toBeDefined();
      const target = new URL(baseUrl ?? 'http://localhost:3000/').origin;
      for (const origin of [target, 'http://localhost:9000', 'https://localhost:3000', 'null']) {
        const localStorage = new Map<string, string>();
        const sessionStorage = new Map<string, string>();
        runInNewContext(`(function () { ${script} })()`, {
          location: { origin },
          window: {
            localStorage: { setItem: localStorage.set.bind(localStorage) },
            sessionStorage: { setItem: sessionStorage.set.bind(sessionStorage) },
          },
        });
        expect([...localStorage]).toEqual(origin === target ? [['token', 'abc']] : []);
        expect([...sessionStorage]).toEqual(
          origin === target ? [['seed', 'synthetic-session']] : [],
        );
      }
    },
  );

  it('inlines the scenario play function body', () => {
    const result = exportPlaywright({
      runMeta: makeIsolationMeta(),
      config: makeConfig(),
      outDir,
    });
    const src = readFileSync(result.written[0]!, 'utf-8');
    expect(src).toContain('button[type=submit]');
    expect(src).toContain('ada@example.com');
    expect(src).toContain('// Scenario play() body inlined');
  });

  it('emits one test.step per criterion as a TODO assertion', () => {
    const result = exportPlaywright({
      runMeta: makeIsolationMeta(),
      config: makeConfig(),
      outDir,
      criteria: [
        {
          description: 'Sign in button is visible',
          status: 'pass',
          reasoning: 'Saw blue button in screenshot.',
        },
        { description: 'Email field is focused', status: 'fail', suggestion: 'Add autoFocus.' },
      ],
    });
    const src = readFileSync(result.written[0]!, 'utf-8');
    expect(src).toContain('"TODO assertion: Sign in button is visible"');
    expect(src).toContain('"TODO assertion: Email field is focused"');
    expect(src).toContain('// Agent saw: Saw blue button in screenshot.');
    expect(src).toContain('// Suggested fix: Add autoFocus.');
  });

  it('emits a generic TODO step when no criteria are passed', () => {
    const result = exportPlaywright({
      runMeta: makeIsolationMeta(),
      config: makeConfig(),
      outDir,
    });
    const src = readFileSync(result.written[0]!, 'utf-8');
    expect(src).toContain('TODO assertion: replace with acceptance check');
    expect(src).toContain('// Prompt: Add a Sign in button');
  });

  it('does not emit toHaveScreenshot when includeVisualAssertions=false', () => {
    const result = exportPlaywright({
      runMeta: makeIsolationMeta(),
      config: makeConfig(),
      outDir,
    });
    const src = readFileSync(result.written[0]!, 'utf-8');
    expect(src).not.toContain('toHaveScreenshot');
  });

  it('emits exactly one toHaveScreenshot when includeVisualAssertions=true', () => {
    const result = exportPlaywright({
      runMeta: makeIsolationMeta(),
      config: makeConfig(),
      outDir,
      includeVisualAssertions: true,
    });
    const src = readFileSync(result.written[0]!, 'utf-8');
    const occurrences = src.match(/toHaveScreenshot/g) ?? [];
    expect(occurrences).toHaveLength(1);
  });

  it('skips existing files without --force', () => {
    const first = exportPlaywright({
      runMeta: makeIsolationMeta(),
      config: makeConfig(),
      outDir,
    });
    expect(first.written).toHaveLength(1);
    const second = exportPlaywright({
      runMeta: makeIsolationMeta(),
      config: makeConfig(),
      outDir,
    });
    expect(second.written).toEqual([]);
    expect(second.skipped[0]).toMatch(/already exists/);
  });

  it('overwrites with --force', () => {
    const first = exportPlaywright({
      runMeta: makeIsolationMeta(),
      config: makeConfig(),
      outDir,
    });
    expect(first.written).toHaveLength(1);
    const second = exportPlaywright({
      runMeta: makeIsolationMeta(),
      config: makeConfig(),
      outDir,
      force: true,
    });
    expect(second.written).toHaveLength(1);
    expect(second.skipped).toEqual([]);
  });

  it('emits a TODO navigate stub (not a real goto) for isolation mode', () => {
    const result = exportPlaywright({
      runMeta: makeIsolationMeta(),
      config: makeConfig(),
      outDir,
    });
    const src = readFileSync(result.written[0]!, 'utf-8');
    expect(src).toContain('// TODO: navigate to a route in your app that renders this component');
  });

  it('handles a play function that fails to serialize without crashing', () => {
    const bound = Function.prototype.bind;
    // Synthetic "play" that toString()s to "[native code]" — bound funcs do.
    // The plain shape exporter accepts is just .toString()-able, so we
    // simulate a bound case by overriding toString.
    const play = function () {
      /* */
    } as unknown as () => void;
    Object.defineProperty(play, 'toString', {
      value: () => 'function () { [native code] }',
    });
    void bound;

    const cfg = makeConfig({
      scenarios: {
        'logged-in': {
          play: play as unknown as ValidityConfig['scenarios'] extends infer X
            ? X extends Record<string, infer V>
              ? V extends { play?: infer P }
                ? P
                : never
              : never
            : never,
        },
      },
    });

    const result = exportPlaywright({
      runMeta: makeIsolationMeta(),
      config: cfg,
      outDir,
    });
    const src = readFileSync(result.written[0]!, 'utf-8');
    expect(src).toContain("Validity couldn't");
    expect(src).toContain('serialize');
  });
});

describe('exportPlaywright (URL mode)', () => {
  let outDir: string;

  beforeEach(() => {
    outDir = mkdtempSync(resolve(tmpdir(), 'validity-export-url-'));
  });

  afterEach(() => {
    rmSync(outDir, { recursive: true, force: true });
  });

  it('navigates to the captured URL directly (no TODO stub)', () => {
    const meta: RunMeta = {
      runId: 'run_url_1',
      createdAt: '2026-01-01T00:00:00.000Z',
      mode: 'url',
      prompt: 'Verify the /dashboard page',
      scenarios: [],
      pages: [
        {
          id: 'dashboard',
          pathId: 'dashboard',
          url: 'http://localhost:5173/dashboard',
          screenshotPath: '/tmp/y.png',
        },
      ],
      diff: { files: [] },
      report: { enabled: true, brand: 'validity' },
    };
    const result = exportPlaywright({
      runMeta: meta,
      config: makeConfig({ mockNetwork: { localStorage: { seed: 'synthetic-local' } } }),
      outDir,
      baseUrl: 'http://localhost:9000',
    });
    expect(result.written).toHaveLength(1);
    const src = readFileSync(result.written[0]!, 'utf-8');
    expect(src).toContain('await page.goto("http://localhost:5173/dashboard")');
    expect(src).toContain('if (location.origin !== "http://localhost:5173") return;');
    expect(src).not.toContain('TODO: navigate to a route in your app');
  });
});

describe('loadReportCriteria', () => {
  it('returns the criteria array from report-meta.json when present', () => {
    const dir = mkdtempSync(resolve(tmpdir(), 'validity-report-meta-'));
    try {
      writeFileSync(
        resolve(dir, 'report-meta.json'),
        JSON.stringify({
          runId: 'r',
          criteria: [{ description: 'one', status: 'pass', reasoning: 'looks good' }],
        }),
      );
      const out = loadReportCriteria(dir);
      expect(out).toHaveLength(1);
      expect(out?.[0]?.description).toBe('one');
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('returns null when the sidecar is missing', () => {
    const dir = mkdtempSync(resolve(tmpdir(), 'validity-no-report-meta-'));
    try {
      const out = loadReportCriteria(dir);
      expect(out).toBeNull();
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('returns null when the sidecar is malformed JSON', () => {
    const dir = mkdtempSync(resolve(tmpdir(), 'validity-bad-report-meta-'));
    try {
      mkdirSync(dir, { recursive: true });
      writeFileSync(resolve(dir, 'report-meta.json'), 'not-json{');
      const out = loadReportCriteria(dir);
      expect(out).toBeNull();
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});
