import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { DataState, MockNetworkConfig, ValidityConfig } from '@validity.ai/verify-spec';
import { entryFile, indexHtml, propsDir, relFromValidity, validityDir } from './paths.js';

export interface PrepareResult {
  validityDir: string;
  entryFile: string;
  indexHtml: string;
  propsDir: string;
  /**
   * The Tailwind **v4** scan shim was emitted into the sandbox
   * (`detectsTailwindV4`). Surfaced on the run's environment record because it
   * is a fidelity fact a reader of the screenshots needs: `false` on a project
   * whose app manifest records Tailwind means the app wires Tailwind through
   * PostCSS (v3), which this shim does not cover — so utilities may simply be
   * missing from the pixels.
   */
  tailwindShim: boolean;
}

function ensureDir(p: string) {
  if (!existsSync(p)) mkdirSync(p, { recursive: true });
}

/**
 * Shared between `prepareSandbox()` (Vite/web) and `prepareExpoWeb()` —
 * writes index.html, validity-msw.ts, the browse-mode index template,
 * and the optional Tailwind v4 shim into `node_modules/.validity/`.
 *
 * The HTML shell is framework-agnostic: the early-error trap and the
 * pre-React scenario seed live in static `<script>` tags that run
 * before any module loads, and the `<div id="root">` is the same mount
 * point for both `createRoot()` (web) and `AppRegistry.runApplication()`
 * (Expo Web via react-native-web).
 *
 * Returns flags the caller's entry.tsx generator needs (whether the
 * Tailwind shim was emitted, whether the browse index template was
 * found) so each generator can wire its imports conditionally.
 */
export interface SharedAssetsResult {
  hasTailwindV4: boolean;
  hasBrowseIndex: boolean;
  hasInspector: boolean;
}

export function writeSharedSandboxAssets(projectRoot: string): SharedAssetsResult {
  const dir = validityDir(projectRoot);

  // index.html — see prepare.ts for the inline rationale on each script.
  writeFileSync(indexHtml(projectRoot), INDEX_HTML_SOURCE);

  // validity-net-bootstrap.ts — applies the fetch/XHR interceptors at
  // module-evaluation time. entry.tsx imports this FIRST (before the user's
  // Wrapper), so globalThis.fetch + XMLHttpRequest are patched before any user
  // module — auth clients, API singletons, provider graphs — can fire a
  // request. Handler wiring is completed later by setupValidityNetwork
  // (validity-msw); until then, requests are HELD rather than passed through.
  writeFileSync(resolve(dir, 'validity-net-bootstrap.ts'), VALIDITY_NET_BOOTSTRAP_SOURCE);

  // validity-msw.ts — network handler layer. Same source for both targets.
  writeFileSync(resolve(dir, 'validity-msw.ts'), VALIDITY_MSW_SOURCE);

  // Browse-mode index template (optional — older sandbox builds may not
  // have shipped it; gate the import behind its presence).
  const browseIndexSource = readBrowseIndexTemplate();
  const hasBrowseIndex = browseIndexSource !== null;
  if (hasBrowseIndex) {
    writeFileSync(resolve(dir, 'validity-index.tsx'), browseIndexSource);
  }

  // In-iframe inspector + theme override. Gated by parent postMessage
  // (idle until enabled), so safe to ship alongside both browse and
  // verify entries.
  const inspectorSource = readInspectorTemplate();
  const hasInspector = inspectorSource !== null;
  if (hasInspector) {
    writeFileSync(resolve(dir, 'validity-inspector.ts'), inspectorSource);
  }

  const hasTailwindV4 = detectsTailwindV4(projectRoot);
  if (hasTailwindV4) {
    // Import the PROJECT'S OWN Tailwind entry stylesheet when one exists —
    // not the bare "tailwindcss" default. Tailwind v4 only emits a utility
    // for a custom `@theme` token (bg-accent, text-accent, …) when the class
    // name appears in scanned content, and the user entry's own build scans
    // from this sandbox's Vite root (node_modules/.validity/) where no
    // project source lives. Importing the user entry HERE puts the custom
    // theme and the project-wide @source scan below in the SAME compiled
    // build; a default-palette-only shim leaves every custom-token utility
    // ungenerated and accent styling silently missing from screenshots.
    const userEntryCss = findTailwindEntryCss(projectRoot);
    const themeImport = userEntryCss
      ? `@import "../../${userEntryCss}";`
      : `@import "tailwindcss";`;
    writeFileSync(
      resolve(dir, 'validity-tailwind-shim.css'),
      `/* Generated by @validity.ai/verify-web. Do not edit.
   Tells Tailwind v4's Oxide scanner to walk the project root for utility
   class names — Vite's root in this sandbox is node_modules/.validity/,
   which would otherwise leave components in src/ invisible to the scan.
   The base of an @source directive is the directory of the CSS file
   containing it, so "../../" from this file points at the project root.
   The first import is the project's own Tailwind entry when found (its
   @theme tokens must compile against THIS build's project-wide scan);
   the bare "tailwindcss" default is the fallback.
*/
${themeImport}
@source "../../**/*.{js,jsx,ts,tsx,mdx,html,vue,svelte}";
@source not "../../node_modules/**";
@source not "../../.git/**";
@source not "../../dist/**";
@source not "../../build/**";
@source not "../../.next/**";
@source not "../../.validity/runs/**";
`,
    );
  }

  return { hasTailwindV4, hasBrowseIndex, hasInspector };
}

/**
 * Locate the in-iframe inspector template shipped alongside this package.
 * Same resolution strategy as readBrowseIndexTemplate — returns null when
 * neither candidate path exists (older sandbox builds didn't ship it).
 */
function readInspectorTemplate(): string | null {
  try {
    const here = dirname(fileURLToPath(import.meta.url));
    const candidates = [
      resolve(here, '..', 'templates', 'validity-inspector.ts'),
      resolve(here, 'templates', 'validity-inspector.ts'),
    ];
    for (const tpl of candidates) {
      if (existsSync(tpl)) return readFileSync(tpl, 'utf-8');
    }
    return null;
  } catch {
    return null;
  }
}

/**
 * Heuristic detection for Tailwind v4 driven by package.json. We can't
 * load the user's vite.config synchronously here (loadConfigFromFile is
 * async, prepareSandbox is not), so we check the dependency declaration
 * which is the same signal in 99% of cases. False positive cost = an
 * extra ~5KB CSS file is generated and unused; false negative cost =
 * Tailwind utilities used in the user's components don't get compiled
 * and screenshots come back unstyled. Bias toward emitting the shim.
 */
export function detectsTailwindV4(projectRoot: string): boolean {
  try {
    const pkg = JSON.parse(readFileSync(resolve(projectRoot, 'package.json'), 'utf-8')) as {
      dependencies?: Record<string, string>;
      devDependencies?: Record<string, string>;
    };
    const deps = { ...(pkg.dependencies ?? {}), ...(pkg.devDependencies ?? {}) };
    return '@tailwindcss/vite' in deps;
  } catch {
    return false;
  }
}

/** `@import "tailwindcss"` (incl. `tailwindcss/utilities`, `source(...)` suffixes). */
const TAILWIND_IMPORT_RE = /@import\s+["']tailwindcss/;

/** Well-known global-CSS locations, probed before the bounded walk. */
const TAILWIND_ENTRY_CANDIDATES = [
  'src/index.css',
  'src/main.css',
  'src/global.css',
  'src/globals.css',
  'src/styles/global.css',
  'src/styles/globals.css',
  'src/app.css',
  'app/globals.css',
  'app/global.css',
  'styles/globals.css',
];

/**
 * Locate the project's Tailwind v4 entry stylesheet — the file with the
 * `@import "tailwindcss"` line (and, typically, the custom `@theme` block).
 * Probes the well-known candidates first, then falls back to a bounded walk
 * of src/, app/, styles/ (depth ≤ 3) for non-standard names. Returns a
 * project-relative '/'-separated path, or null (shim then imports the bare
 * "tailwindcss" default — pre-existing behavior).
 */
export function findTailwindEntryCss(projectRoot: string): string | null {
  for (const rel of TAILWIND_ENTRY_CANDIDATES) {
    try {
      const abs = resolve(projectRoot, rel);
      if (existsSync(abs) && TAILWIND_IMPORT_RE.test(readFileSync(abs, 'utf-8'))) return rel;
    } catch {
      // unreadable candidate — keep probing
    }
  }
  for (const root of ['src', 'app', 'styles']) {
    const hit = walkForTailwindEntry(resolve(projectRoot, root), projectRoot, 3);
    if (hit) return hit;
  }
  return null;
}

function walkForTailwindEntry(dirAbs: string, projectRoot: string, depth: number): string | null {
  if (depth < 0) return null;
  let entries;
  try {
    entries = readdirSync(dirAbs, { withFileTypes: true });
  } catch {
    return null;
  }
  for (const e of entries) {
    if (e.name === 'node_modules' || e.name.startsWith('.')) continue;
    const abs = resolve(dirAbs, e.name);
    if (e.isFile() && e.name.endsWith('.css')) {
      try {
        if (TAILWIND_IMPORT_RE.test(readFileSync(abs, 'utf-8'))) {
          return relative(projectRoot, abs).split(sep).join('/');
        }
      } catch {
        // unreadable — keep walking
      }
    } else if (e.isDirectory()) {
      const hit = walkForTailwindEntry(abs, projectRoot, depth - 1);
      if (hit) return hit;
    }
  }
  return null;
}

/**
 * Locate the browse-mode Index template shipped alongside this package.
 *
 * Three resolution paths in order:
 *   1. Dev / monorepo:   `<sandbox>/src/prepare.ts` → `../templates/`
 *   2. Published tsc:    `<sandbox>/dist/prepare.js` → `../templates/`
 *   3. Esbuild bundle:   `<install>/cli.js` → `templates/` (sibling, no `..`)
 *
 * The third is the production-install path — the CLI bundles
 * the sandbox into `cli.js` so `import.meta.url` points at the install root,
 * not at a `dist/` subdir. The installer copies `templates/browse-index.tsx`
 * alongside `cli.js` so this lookup succeeds. Returns the source string
 * or null when nothing's found — caller falls back to a no-index entry.
 */
function readBrowseIndexTemplate(): string | null {
  try {
    const here = dirname(fileURLToPath(import.meta.url));
    const candidates = [
      resolve(here, '..', 'templates', 'browse-index.tsx'),
      resolve(here, 'templates', 'browse-index.tsx'),
    ];
    for (const tpl of candidates) {
      if (existsSync(tpl)) return readFileSync(tpl, 'utf-8');
    }
    return null;
  } catch {
    return null;
  }
}

/** Stripped-down view of MockNetworkConfig sent to the browser — drops cookies/storage which Playwright handles. */
function browserNetworkPayload(cfg: MockNetworkConfig | undefined, dataState?: DataState) {
  // DEFAULT 'populate' (list/feed URLs render synthetic content; everything else
  // stays crash-safe). Opt out with `mockNetwork.fallback: 'permissive'`.
  // `dataState` rides the scenario payload so a scenario-level force (e.g. a
  // 'server-down' scenario = dataState 'error') reaches the in-page MSW layer;
  // the verify-time ?dataState= param wins over it (see setupValidityNetwork).
  if (!cfg) {
    return {
      fallback: 'populate' as const,
      handlers: [],
      ...(dataState ? { dataState } : {}),
    };
  }
  return {
    fallback: cfg.fallback ?? 'populate',
    handlers: cfg.handlers ?? [],
    ...(dataState ? { dataState } : {}),
  };
}

export function prepareSandbox(projectRoot: string, config: ValidityConfig): PrepareResult {
  const dir = validityDir(projectRoot);
  ensureDir(dir);
  ensureDir(propsDir(projectRoot));

  // .gitignore inside validity dir to keep generated files out of git regardless
  writeFileSync(resolve(dir, '.gitignore'), '*\n');

  const wrapperAbs = resolve(projectRoot, config.wrapper);
  const wrapperRel = relFromValidity(projectRoot, wrapperAbs).replace(/\.(tsx?|jsx?)$/, '');

  // Pre-serialize the network configs into the entry. Cookies/storage are NOT
  // here — Playwright handles those via addCookies/addInitScript, before the
  // page even loads.
  const baseNetwork = browserNetworkPayload(config.mockNetwork);
  const scenariosNetwork: Record<string, ReturnType<typeof browserNetworkPayload>> = {};
  for (const [name, scenario] of Object.entries(config.scenarios ?? {})) {
    scenariosNetwork[name] = browserNetworkPayload(scenario.mockNetwork, scenario.dataState);
  }

  // Per-component fixtures map (props only — play functions don't survive a
  // JSON round-trip and stacked rendering doesn't use them anyway). entry.tsx
  // looks up `__VALIDITY_FIXTURES__[componentPath][fixtureName]` to apply
  // the right props to each sibling in stacked mode.
  const fixturesByComponent: Record<string, Record<string, unknown>> = {};
  for (const [path, entry] of Object.entries(config.components ?? {})) {
    if (!entry.fixtures) continue;
    const map: Record<string, unknown> = {};
    for (const [fxName, fx] of Object.entries(entry.fixtures)) {
      map[fxName] = fx.props ?? {};
    }
    fixturesByComponent[path] = map;
  }

  // index.html + validity-msw.ts + browse index template + Tailwind shim —
  // emitted via the shared helper. Both prepareSandbox (web) and
  // prepareExpoWeb call this; the index.html mount point (`<div id="root">`)
  // works for createRoot() and AppRegistry.runApplication() alike.
  const { hasTailwindV4, hasBrowseIndex, hasInspector } = writeSharedSandboxAssets(projectRoot);

  // entry.tsx — top-level awaits the interceptor setup BEFORE the dynamic
  // component import resolves, so even module-side-effect fetches (e.g., a
  // singleton API client constructed at module top) get intercepted.
  const baseNetworkJson = JSON.stringify(baseNetwork);
  const scenariosNetworkJson = JSON.stringify(scenariosNetwork);
  const mocksJson = JSON.stringify(config.mocks ?? {});
  const fixturesJson = JSON.stringify(fixturesByComponent);

  const tailwindShimImport = hasTailwindV4 ? "import './validity-tailwind-shim.css';\n" : '';

  // Index page lives only when its template was found. Importing a
  // non-existent module breaks Vite — gate the import behind the
  // template's presence.
  const browseIndexImport = hasBrowseIndex ? "import { Index } from './validity-index';\n" : '';

  // In-iframe inspector — idle until parent posts an enable message, so
  // safe to import in verify mode too. Gate behind template presence so
  // older sandbox builds don't break the entry.
  const inspectorImport = hasInspector
    ? "import { startValidityInspector } from './validity-inspector';\n"
    : '';
  const inspectorBoot = hasInspector ? 'startValidityInspector();\n' : '';

  writeFileSync(
    entryFile(projectRoot),
    `// FIRST import, on purpose: this side-effect module applies the fetch/XHR
// interceptors synchronously at eval time — BEFORE the Wrapper import below
// pulls in the user's provider graph (auth clients, API singletons). ES module
// imports evaluate depth-first in source order, so anything the Wrapper fetches
// at module-eval lands on the already-patched globals, not the real network.
import './validity-net-bootstrap';
${tailwindShimImport}import React, { useEffect, useState } from 'react';
import * as ReactDOMClient from 'react-dom/client';
import Wrapper from '${wrapperRel}';
import { setupValidityNetwork } from './validity-msw';
${browseIndexImport}${inspectorImport}

declare global {
  interface Window {
    __VALIDITY_MOCKS__?: any;
    __VALIDITY_BASE_NETWORK__?: any;
    __VALIDITY_SCENARIOS__?: Record<string, any>;
    __VALIDITY_FIXTURES__?: Record<string, Record<string, Record<string, unknown>>>;
    __VALIDITY_VIEWS__?: Record<
      string,
      {
        title?: string;
        description?: string;
        layout?: 'stack' | 'grid';
        items: Array<{
          componentPath: string;
          fixtureName?: string;
          props?: Record<string, unknown>;
          label?: string;
          frame?: string;
        }>;
      }
    >;
    __VALIDITY_UNMATCHED__?: string[];
    __VALIDITY_PROFILE__?: Array<{
      phase: string;
      actualDuration: number;
      baseDuration: number;
      startTime: number;
      commitTime: number;
    }>;
    __VALIDITY_PERF_READY_MS__?: number;
    __VALIDITY_PERF_BOOT_MS__?: number;
    __VALIDITY_GET_PERF__?: () => Record<string, number>;
    __validityReady?: boolean;
  }
}

// Perf origin. Everything the HARNESS costs — Vite's first-request transform of
// this module graph, browser JIT, the net-bootstrap + msw + Wrapper imports
// above (ES imports evaluate depth-first, so they are all already done) — lands
// BEFORE this line. Stamping here lets __VALIDITY_GET_PERF__ subtract it, so
// readyMs measures the component's own load+mount instead of the sandbox's cold
// start. Without it, whichever component rendered FIRST in a session ate ~1s of
// warm-up and false-failed any budget under that floor.
try {
  window.__VALIDITY_PERF_BOOT_MS__ = performance.now();
} catch (_) {
  /* no perf clock — readyMs stays navigation-relative */
}

window.__VALIDITY_MOCKS__ = ${mocksJson};
window.__VALIDITY_BASE_NETWORK__ = ${baseNetworkJson};
window.__VALIDITY_SCENARIOS__ = ${scenariosNetworkJson};
window.__VALIDITY_FIXTURES__ = ${fixturesJson};
window.__VALIDITY_UNMATCHED__ = [];
window.__VALIDITY_PROFILE__ = [];

// Performance instrumentation. A <React.Profiler> wraps each rendered
// component (see render sites below) and pushes one entry per commit into
// __VALIDITY_PROFILE__; capture.ts (passive metrics) and the spec check
// executor (expect.performance) both call __VALIDITY_GET_PERF__ to fold these
// commits — plus Navigation/Paint Timing — into a flat PerformanceMetrics-shaped
// object. Perf is observational, so every read is defensive and must never
// throw into a render. MIRROR any change here in prepare-expo-web.ts.
const __validityOnRender = (
  _id: string,
  phase: string,
  actualDuration: number,
  baseDuration: number,
  startTime: number,
  commitTime: number,
) => {
  try {
    (window.__VALIDITY_PROFILE__ as Array<Record<string, unknown>>).push({
      phase,
      actualDuration,
      baseDuration,
      startTime,
      commitTime,
    });
  } catch (_) {
    /* perf is best-effort */
  }
};
window.__VALIDITY_GET_PERF__ = () => {
  const out: Record<string, number> = {};
  try {
    const nav = performance.getEntriesByType('navigation')[0] as
      | { loadEventEnd?: number; domContentLoadedEventEnd?: number }
      | undefined;
    if (nav) {
      // OR (not nullish-coalescing) is deliberate: loadEventEnd reads 0 until
      // the load event fires, so a 0 must fall back to domContentLoadedEventEnd
      // rather than be kept.
      const load = nav.loadEventEnd || nav.domContentLoadedEventEnd || 0;
      if (load > 0) out.loadMs = Math.round(load);
    }
    const fcp = performance
      .getEntriesByType('paint')
      .find((e) => e.name === 'first-contentful-paint');
    if (fcp) out.firstContentfulPaintMs = Math.round(fcp.startTime);
  } catch (_) {
    /* Navigation/Paint Timing unavailable */
  }
  if (typeof window.__VALIDITY_PERF_READY_MS__ === 'number') {
    // Subtract the harness's own boot cost so readyMs is the COMPONENT's
    // load+mount, not the sandbox cold start. Clamped at 0: the two stamps come
    // off the same monotonic clock in program order, so ready < boot is
    // impossible — the clamp only guards a missing/failed boot stamp.
    const boot =
      typeof window.__VALIDITY_PERF_BOOT_MS__ === 'number' ? window.__VALIDITY_PERF_BOOT_MS__ : 0;
    if (boot > 0) out.harnessBootMs = Math.round(boot);
    out.readyMs = Math.max(0, Math.round(window.__VALIDITY_PERF_READY_MS__ - boot));
  }
  try {
    const commits = (window.__VALIDITY_PROFILE__ ?? []) as Array<{
      phase: string;
      actualDuration: number;
    }>;
    out.commitCount = commits.length;
    // Profiler commit durations keep 2 decimals on purpose — sub-ms precision
    // matters against tight budgets (e.g. a 16ms frame); the coarse
    // Navigation/Paint timings above are integer-rounded.
    const mount = commits.find((c) => c.phase === 'mount');
    if (mount) out.mountMs = Math.round(mount.actualDuration * 100) / 100;
    const updates = commits.filter((c) => c.phase === 'update' || c.phase === 'nested-update');
    if (updates.length > 0) {
      out.updateMs = Math.round(Math.max(...updates.map((c) => c.actualDuration)) * 100) / 100;
      out.updateTotalMs =
        Math.round(updates.reduce((s, c) => s + c.actualDuration, 0) * 100) / 100;
    }
  } catch (_) {
    /* profiler data unavailable */
  }
  return out;
};

// Defense-in-depth: assert there's exactly ONE React module record in this
// window. Two records is the classic "Cannot read properties of null
// (reading 'useState')" failure mode — React-DOM sets the hooks dispatcher
// on its own React reference, and any child using the OTHER reference reads
// a null dispatcher. Catches dep-reoptimize splits, alias mistakes, pnpm
// hoisting changes, and any user plugin doing surprising resolution. Render
// a clear in-canvas error rather than letting the cryptic null-dispatcher
// trace surface inside a deep child.
const __validityDynReact = await import('react');
const __validityDynReactDom = await import('react-dom/client');
const __validityReactStatic: any = (React as any);
const __validityReactDyn: any = (__validityDynReact as any).default ?? __validityDynReact;
const __validityReactDomStatic: any = ReactDOMClient as any;
const __validityReactDomDyn: any =
  (__validityDynReactDom as any).default ?? __validityDynReactDom;
if (
  __validityReactStatic !== __validityReactDyn ||
  typeof __validityReactStatic.useState !== 'function' ||
  __validityReactDomStatic.createRoot !== __validityReactDomDyn.createRoot
) {
  const staticVer = __validityReactStatic?.version ?? 'unknown';
  const dynVer = __validityReactDyn?.version ?? 'unknown';
  document.body.innerHTML =
    '<pre data-validity-error="true" data-validity-error-source="sandbox" ' +
    'style="padding:16px;color:#b00020;font:13px ui-monospace,Menlo,monospace;white-space:pre-wrap;">' +
    'Validity sandbox error: two copies of React are loaded in this window.\\n\\n' +
    'This usually means Vite re-ran its dep optimizer mid-session and a stale\\n' +
    'React module URL is still referenced. Try:\\n' +
    '  - restarting "validity browse" (clears the warm cache)\\n' +
    '  - removing node_modules/.validity/.vite-cache\\n' +
    '  - adding the offending package to vite.config.ts > optimizeDeps.include\\n\\n' +
    'Static React  : version ' + staticVer + '\\n' +
    'Dynamic React : version ' + dynVer +
    '</pre>';
  document.documentElement.setAttribute('data-validity-ready', 'true');
  throw new Error('Validity: duplicate React detected at boot');
}
const createRoot = ReactDOMClient.createRoot;

// Validity: auto-mock React contexts whose Provider is mounted below the
// wrapper splice point (commonly inside App.tsx) and is therefore absent in
// the sandbox. A consumer like useGlobalSync() typically runs
//   const ctx = useContext(C); if (!ctx) throw new Error('must be used within ...')
// which would crash the whole render. We seed createContext's default with a
// deep-default proxy (instead of null/undefined) so that guard passes and any
// ctx.some.deep.value read resolves to 0 / [] / '' / another proxy. A real
// Provider, when present, still supplies its own value and wins -- this only
// changes the default used when no Provider is mounted above the consumer.
//
// Placement matters: Vite compiles "import { createContext } from 'react'" to
// a property read on this same default React object at each module's eval
// time. Screens are imported dynamically (inside effects, below) AFTER this
// statement runs, so their named createContext imports pick up the patched
// version too. Statically-imported wrapper contexts evaluate earlier, but
// their Providers are present in the generated wrapper, so the seeded default
// is never consulted for them.
// NOTE: the deep-default proxy factory lives in the validity-msw module and is
// exposed on window (set during that module's import, before this body runs) —
// it is NOT in entry scope, so we reach it via window.__VALIDITY_DEEP_DEFAULT__
// exactly like hydrateProxySentinels does. If it's somehow unavailable we fall
// back to the original default (null/undefined) so behavior degrades safely.
const __validityRealCreateContext = React.createContext;
(React as any).createContext = function validityCreateContext(defaultValue: unknown) {
  const proxyFactory = window.__VALIDITY_DEEP_DEFAULT__;
  const seeded =
    (defaultValue === undefined || defaultValue === null) && proxyFactory
      ? proxyFactory()
      : defaultValue;
  return (__validityRealCreateContext as any)(seeded);
};

// The fetch/XHR interceptors are ALREADY applied (validity-net-bootstrap, the
// first import above). This top-level await WIRES the per-render handlers into
// them and resolves the bootstrap's ready-promise — draining any request that
// fired before this point (a module-eval fetch from the statically-imported
// Wrapper graph is held on that promise, never passed through to the network).
// It stays a top-level await so handlers are guaranteed live before the first
// React commit below.
const params = new URLSearchParams(window.location.search);
const scenarioId = params.get('scenario') ?? undefined;
// Color-scheme (theme) override from the verify run's ?theme= param. Apply the
// class/attr/style conventions BEFORE the first React commit so a Tailwind
// 'class'-strategy app paints in the right theme on first frame; the value is
// also passed to <Wrapper colorScheme> below for ThemeProvider apps. Undefined
// when the theme axis is off (single default-theme render).
const colorScheme = params.get('theme') ?? undefined;
if (colorScheme === 'light' || colorScheme === 'dark') {
  const root = document.documentElement;
  root.classList.toggle('dark', colorScheme === 'dark');
  root.setAttribute('data-validity-theme', colorScheme);
  root.style.colorScheme = colorScheme;
}
// Forced data-state axis (A2): the verify run's ?dataState= param overrides
// handler matching inside the MSW layer (loading hangs / empty / error).
const dataState = params.get('dataState') ?? undefined;
const baseNetwork = window.__VALIDITY_BASE_NETWORK__;
const scenarioNetwork = scenarioId ? window.__VALIDITY_SCENARIOS__?.[scenarioId] : undefined;
await setupValidityNetwork({ base: baseNetwork, scenario: scenarioNetwork, dataState });

// Browse mode also wants server-inferred fixtures (synthesized from prop
// types by /__validity/api/config). Bake-time fixtures cover the explicit
// config, but the canvas can ALSO render components whose props were
// auto-inferred — and those fixtures only exist on the server. Fetch the
// config and merge any \`inferred: true\` fixture into __VALIDITY_FIXTURES__
// alongside whatever the user authored. Failure is silent: in verify mode
// the endpoint is still there, but if the request fails for any reason,
// the bake-time fixtures still cover the explicit verify renders.
try {
  const cfgRes = await fetch('/__validity/api/config');
  if (cfgRes.ok) {
    const cfg = (await cfgRes.json()) as {
      components?: Record<
        string,
        {
          fixtures?: Record<
            string,
            { props?: Record<string, unknown>; inferred?: boolean }
          >;
        }
      >;
      _views?: {
        views?: Array<{
          name: string;
          title?: string;
          description?: string;
          layout?: 'stack' | 'grid';
          items: Array<{
            componentPath: string;
            fixtureName?: string;
            props?: Record<string, unknown>;
            label?: string;
            frame?: string;
          }>;
        }>;
      };
    };
    const map = window.__VALIDITY_FIXTURES__ ?? {};
    for (const [path, entry] of Object.entries(cfg.components ?? {})) {
      const fixtures = entry?.fixtures ?? {};
      if (Object.keys(fixtures).length === 0) continue;
      const existing = map[path] ?? {};
      for (const [fxName, fx] of Object.entries(fixtures)) {
        // User-authored fixtures are baked in at prepare time and live
        // in __VALIDITY_FIXTURES__ already. Don't overwrite them.
        if (fx?.inferred && !(fxName in existing)) {
          existing[fxName] = fx.props ?? {};
        }
      }
      map[path] = existing;
    }
    window.__VALIDITY_FIXTURES__ = map;

    // Views — author-defined compositions surfaced under _views in the
    // config response. Stash by name so the App() can look them up
    // synchronously when handling ?view=<name>.
    const viewMap: NonNullable<typeof window.__VALIDITY_VIEWS__> = {};
    for (const v of cfg._views?.views ?? []) {
      viewMap[v.name] = {
        title: v.title,
        description: v.description,
        layout: v.layout,
        items: v.items,
      };
    }
    window.__VALIDITY_VIEWS__ = viewMap;
  }
} catch {
  /* /__validity/api/config absent — fall back to bake-time fixtures. */
}

const componentMap = import.meta.glob('../../**/*.{tsx,jsx}');

async function loadProps(propsId: string | null): Promise<Record<string, unknown>> {
  if (!propsId) return {};
  try {
    const res = await fetch('/props/' + propsId + '.json');
    if (!res.ok) return {};
    return (await res.json()) as Record<string, unknown>;
  } catch {
    return {};
  }
}

/**
 * Decode the browse-mode \`?overrides=\` URL param into a props record. The
 * payload is JSON, encoded either as URL-safe base64 (the normal browser
 * path — \`btoa\` after a UTF-8 widening pass) or as percent-encoded JSON
 * (the SSR/test fallback). Failures resolve to an empty record so a
 * malformed URL never blocks rendering.
 */
function decodeOverrides(raw: string | null): Record<string, unknown> {
  if (!raw) return {};
  let json: string | null = null;
  try {
    json = decodeURIComponent(escape(atob(raw)));
  } catch {
    // Not base64 — fall through to the percent-encoded path.
  }
  if (json === null) {
    try {
      json = decodeURIComponent(raw);
    } catch {
      return {};
    }
  }
  try {
    const parsed = JSON.parse(json);
    if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
      return parsed as Record<string, unknown>;
    }
    return {};
  } catch {
    return {};
  }
}

/**
 * Walk a (potentially nested) props object and replace any
 * "__VALIDITY_PROXY__" sentinel strings with a deep-default Proxy.
 * The sentinel exists because the inference layer (which produces JSON)
 * can't carry a Proxy directly, but a Proxy is the only value that
 * lets a component freely access \`prop.foo.bar.length\` without
 * crashing when the prop's TS type couldn't be statically resolved.
 *
 * Idempotent — values that aren't the sentinel pass through unchanged.
 */
function hydrateProxySentinels(value: unknown): unknown {
  if (value === '__VALIDITY_PROXY__') {
    return window.__VALIDITY_DEEP_DEFAULT__?.() ?? null;
  }
  if (Array.isArray(value)) {
    return value.map(hydrateProxySentinels);
  }
  if (value && typeof value === 'object') {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
      out[k] = hydrateProxySentinels(v);
    }
    return out;
  }
  return value;
}

function resolveComponent(componentPath: string): (() => Promise<any>) | null {
  // componentPath is project-relative: 'src/components/Header.tsx'
  // glob keys are validity-dir-relative: '../../src/components/Header.tsx'
  const candidate = '../../' + componentPath.replace(/^\\/+/, '');
  if (componentMap[candidate]) return componentMap[candidate];
  // case-insensitive fallback
  const lower = candidate.toLowerCase();
  for (const [key, loader] of Object.entries(componentMap)) {
    if (key.toLowerCase() === lower) return loader;
  }
  return null;
}

/**
 * Pick the right export from a dynamically imported component module.
 *
 * Order of preference:
 *   1. \`default\` export.
 *   2. Named export matching the file basename (e.g. ChessBoard.tsx →
 *      \`ChessBoard\`). This is the most common React convention and is
 *      load-bearing for files without a default export.
 *   3. First named export whose value is a function and whose key starts
 *      with an uppercase letter (component naming convention).
 *   4. First value in \`Object.values(mod)\` as a last resort.
 *
 * The first-value fallback used to be the only resolution path, which
 * surfaced as "Element type is invalid: expected a string ... but got:
 * undefined" whenever the module's value order put a non-component
 * export (a constant or helper hoisted re-export) first.
 */
function pickComponentExport(mod: any, componentPath: string): any {
  if (mod?.default !== undefined) return mod.default;
  const base = componentPath.split('/').pop()?.replace(/\\.(tsx?|jsx?)$/, '') ?? '';
  if (base && mod && typeof mod === 'object' && base in mod) {
    return mod[base];
  }
  if (mod && typeof mod === 'object') {
    for (const [name, value] of Object.entries(mod)) {
      if (/^[A-Z]/.test(name) && typeof value === 'function') return value;
    }
    return Object.values(mod)[0];
  }
  return undefined;
}

interface StackedFixture {
  id: string;
  props: Record<string, unknown>;
}

/**
 * Resolve the list of fixtures for the stacked render path. The URL
 * carries fixture names; props for each come from the injected
 * \`__VALIDITY_FIXTURES__[componentPath]\` map. Names without a matching
 * fixture entry render with empty props (with a label warning the user).
 */
function resolveStackedFixtures(componentPath: string, fixtureNames: string[]): StackedFixture[] {
  const map = window.__VALIDITY_FIXTURES__?.[componentPath] ?? {};
  return fixtureNames.map((id) => ({ id, props: (map[id] as Record<string, unknown>) ?? {} }));
}

type ViewItemResult =
  | {
      ok: true;
      label: string;
      componentPath: string;
      Component: any;
      props: Record<string, unknown>;
    }
  | {
      ok: false;
      label: string;
      componentPath: string;
      error: string;
    };

type AppState =
  | { kind: 'loading' }
  | { kind: 'error'; message: string }
  | { kind: 'ready-index' }
  | { kind: 'ready-single'; Component: any; baseProps: Record<string, unknown> }
  | { kind: 'ready-stacked'; Component: any; fixtures: StackedFixture[] }
  | {
      kind: 'ready-view';
      viewName: string;
      title: string;
      layout: 'stack' | 'grid';
      results: ViewItemResult[];
    };

/**
 * Class-component error boundary. We need two — an inner one around the
 * user component (errors here = component bugs) and an outer one around
 * the Wrapper (errors here = wrapper bugs, usually from cloned providers
 * we couldn't fully reproduce). Differentiated by the \`source\` prop in
 * the rendered fallback, so the capture step's innerText read includes
 * a clear attribution.
 */
class ValidityErrorBoundary extends React.Component<
  { children: React.ReactNode; source: 'wrapper' | 'component' },
  { error: Error | null }
> {
  state: { error: Error | null } = { error: null };
  static getDerivedStateFromError(error: Error) {
    return { error };
  }
  render() {
    if (this.state.error) {
      const message = this.state.error.message || String(this.state.error);
      const stack = this.state.error.stack ?? message;
      const isWrapper = this.props.source === 'wrapper';
      // Dedup'd list of network calls Validity intercepted but had no
      // explicit handler for. Almost every "Cannot read properties of
      // undefined" error in a real-app component traces back to a fetched
      // endpoint returning the wrong shape — surfacing the unmatched URLs
      // here turns "I need a fixture or something?" into "ah, I need to
      // mock /analyze/.../progress."
      const unmatched = Array.from(
        new Set(window.__VALIDITY_UNMATCHED__ ?? []),
      ).slice(0, 12);
      // Friendly card that explains the most likely cause (a missing
      // provider / router / data mock) instead of dumping the raw red
      // stack. Auto-inferred renders frequently throw because the
      // component reads from useParams / useContext / useQuery — the
      // synthesized props can't satisfy any of that. Show the user
      // what's actionable; keep the stack one click away for debugging.
      // The data-validity-error attribute stays so capture.ts and the
      // integration tests still detect the error state.
      return (
        <div
          data-validity-error="true"
          data-validity-error-source={this.props.source}
          style={{
            margin: 16,
            padding: '18px 22px',
            background: '#fffbeb',
            border: '1px dashed #f59e0b',
            borderRadius: 8,
            font:
              '13px ui-sans-serif, -apple-system, system-ui, "Segoe UI", Roboto, sans-serif',
            color: '#0f172a',
            maxWidth: 680,
            display: 'flex',
            flexDirection: 'column',
            gap: 10,
            boxSizing: 'border-box',
          }}
        >
          <div
            style={{
              fontSize: 11,
              textTransform: 'uppercase',
              letterSpacing: '0.08em',
              color: '#b45309',
              fontWeight: 600,
            }}
          >
            {isWrapper ? 'Validity wrapper error' : 'This component threw at runtime'}
          </div>
          <p style={{ margin: 0, fontSize: 13, lineHeight: 1.55 }}>
            {isWrapper
              ? 'The cloned provider tree threw while rendering. Check .validity/wrapper.tsx — usually a provider needs context (auth, theme, store) that Validity has not seeded.'
              : unmatched.length > 0
                ? 'This component fetched data Validity did not have a handler for. Most "Cannot read properties of undefined" errors here trace to a real network call that came back empty. Add a handler in .validity/config.ts for one of these endpoints:'
                : 'It probably needs more than props — a context provider (auth, theme, query client), a router, or a mocked API response. Define a fixture under .validity/config.ts with a wrapper or seeded data.'}
          </p>
          {unmatched.length > 0 && (
            <ul
              style={{
                margin: 0,
                paddingLeft: 18,
                fontSize: 12,
                lineHeight: 1.55,
                fontFamily:
                  'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
                color: '#1e293b',
                background: 'rgba(15, 23, 42, 0.04)',
                padding: '8px 12px 8px 26px',
                borderRadius: 4,
                maxHeight: 160,
                overflow: 'auto',
              }}
            >
              {unmatched.map((u, i) => (
                <li key={i} style={{ wordBreak: 'break-all' }}>{u}</li>
              ))}
            </ul>
          )}
          <code
            style={{
              fontSize: 12,
              color: '#b00020',
              fontFamily:
                'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
              background: 'rgba(176, 0, 32, 0.06)',
              padding: '6px 8px',
              borderRadius: 4,
              wordBreak: 'break-word',
            }}
          >
            {message}
          </code>
          <details style={{ marginTop: 2 }}>
            <summary
              style={{
                cursor: 'pointer',
                fontSize: 12,
                color: '#64748b',
                fontWeight: 500,
                userSelect: 'none',
              }}
            >
              Show stack trace
            </summary>
            <pre
              style={{
                marginTop: 8,
                padding: 10,
                background: 'rgba(15, 23, 42, 0.04)',
                border: '1px solid rgba(15, 23, 42, 0.08)',
                borderRadius: 4,
                font:
                  '11px ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
                color: '#475569',
                whiteSpace: 'pre-wrap',
                maxHeight: 240,
                overflow: 'auto',
                margin: 0,
              }}
            >
              {stack}
            </pre>
          </details>
        </div>
      );
    }
    return this.props.children as React.ReactElement;
  }
}

function App() {
  const [state, setState] = useState<AppState>({ kind: 'loading' });
  // Browse-mode prop overrides are kept in their own state so the parent
  // page can push updates over postMessage without forcing the iframe to
  // re-navigate (which would FOUC). The initial value is whatever the URL
  // carried at mount; subsequent changes come from validity:overrides:set
  // messages from the host browse-index. Verify never touches this path —
  // verify always loads with the propsId baked into the URL.
  const [overrides, setOverrides] = useState<Record<string, unknown>>(
    () => decodeOverrides(params.get('overrides')),
  );

  useEffect(() => {
    const onMessage = (event: MessageEvent): void => {
      const data = (event.data ?? null) as { type?: string; overrides?: unknown } | null;
      if (!data || data.type !== 'validity:overrides:set') return;
      const incoming =
        data.overrides && typeof data.overrides === 'object' && !Array.isArray(data.overrides)
          ? (data.overrides as Record<string, unknown>)
          : {};
      setOverrides(hydrateProxySentinels(incoming) as Record<string, unknown>);
    };
    window.addEventListener('message', onMessage);
    return () => window.removeEventListener('message', onMessage);
  }, []);

  useEffect(() => {
    const componentPath = params.get('component');
    const propsId = params.get('propsId');
    const fixtureName = params.get('fixture');
    const viewName = params.get('view');
    const stackedNames = (params.get('fixtures') ?? '')
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean);

    // ?view=NAME — render the view's items. With ?frame=KEY we render only the
    // items in that one frame group (the host mounts one iframe per frame);
    // without it we render the whole view stacked (bridge/fallback path). Frame
    // grouping key MUST match the host: an item explicit frame, else
    // "auto:" + componentPath. Views never combine with propsId/fixture/stack.
    if (viewName) {
      const view = window.__VALIDITY_VIEWS__?.[viewName];
      if (!view) {
        setState({ kind: 'error', message: 'View not found: ' + viewName });
        return;
      }
      const frameKey = params.get('frame');
      const groupKeyFor = (it: { componentPath: string; frame?: string }): string =>
        it.frame ?? 'auto:' + it.componentPath;
      const itemsToRender = frameKey
        ? view.items.filter((it) => groupKeyFor(it) === frameKey)
        : view.items;
      if (frameKey && itemsToRender.length === 0) {
        setState({ kind: 'error', message: 'Frame not found in view: ' + frameKey });
        return;
      }
      const layout: 'stack' | 'grid' = view.layout === 'grid' ? 'grid' : 'stack';
      const tasks = itemsToRender.map(async (item, idx): Promise<ViewItemResult> => {
        const labelFallback =
          item.label ??
          (item.componentPath.split('/').pop() ?? item.componentPath) +
            (item.fixtureName ? ' · ' + item.fixtureName : ' · ' + (idx + 1));
        const loader = resolveComponent(item.componentPath);
        if (!loader) {
          return { ok: false, label: labelFallback, componentPath: item.componentPath, error: 'Component not found in glob: ' + item.componentPath };
        }
        try {
          const mod = await loader();
          const Component = pickComponentExport(mod, item.componentPath);
          if (!Component) {
            return { ok: false, label: labelFallback, componentPath: item.componentPath, error: 'No exported component in ' + item.componentPath };
          }
          let props: Record<string, unknown> = {};
          if (item.fixtureName) {
            const map = window.__VALIDITY_FIXTURES__?.[item.componentPath];
            const fxProps = map?.[item.fixtureName] as Record<string, unknown> | undefined;
            if (fxProps) props = { ...fxProps };
          }
          if (item.props) {
            props = { ...props, ...item.props };
          }
          return {
            ok: true,
            label: labelFallback,
            componentPath: item.componentPath,
            Component,
            props: hydrateProxySentinels(props) as Record<string, unknown>,
          };
        } catch (err) {
          return {
            ok: false,
            label: labelFallback,
            componentPath: item.componentPath,
            error: String((err as Error)?.message ?? err),
          };
        }
      });
      Promise.all(tasks)
        .then((results) =>
          setState({
            kind: 'ready-view',
            viewName,
            // In frame mode the host's frame chrome shows the label, so we
            // suppress the in-iframe title to avoid a duplicate header.
            title: frameKey ? '' : view.title ?? viewName,
            layout,
            results,
          }),
        )
        .catch((err) => setState({ kind: 'error', message: String(err?.message ?? err) }));
      return;
    }

    if (!componentPath) {
      // Browse-mode home page. Verify never hits this branch because it
      // always sets ?component= when navigating. If the Index template
      // isn't available (older build), fall through to the legacy error
      // so the user sees a clear message instead of a blank page.
      ${hasBrowseIndex ? 'setState({ kind: "ready-index" });' : `setState({ kind: 'error', message: 'No ?component= query parameter provided.' });`}
      return;
    }

    const loader = resolveComponent(componentPath);
    if (!loader) {
      setState({
        kind: 'error',
        message: 'Component not found in glob: ' + componentPath,
      });
      return;
    }

    if (stackedNames.length > 0) {
      // Stacked-fixture mode — render every named fixture as a sibling
      // under the wrapper. No /props/<id>.json fetch needed; the props
      // come from the injected __VALIDITY_FIXTURES__ map.
      loader()
        .then((mod) => {
          const Component = pickComponentExport(mod, componentPath);
          if (!Component) {
            setState({ kind: 'error', message: 'No exported component in ' + componentPath });
            return;
          }
          const fixtures = resolveStackedFixtures(componentPath, stackedNames).map(
            (fx) => ({ ...fx, props: hydrateProxySentinels(fx.props) as Record<string, unknown> }),
          );
          setState({ kind: 'ready-stacked', Component, fixtures });
        })
        .catch((err) => setState({ kind: 'error', message: String(err?.message ?? err) }));
      return;
    }

    // Single-fixture render. propsId takes precedence (the verify path
    // always writes one), then the fixture-name lookup (browse canvas
    // uses this), then an empty object.
    //
    // The fixture-name lookup is what makes server-inferred fixtures
    // work: prepareSandbox's runtime fetch merges them into
    // __VALIDITY_FIXTURES__, so \`?fixture=auto\` finds the synthesized
    // props here without any explicit propsId being written.
    const resolveSingleProps = async (): Promise<Record<string, unknown>> => {
      if (propsId) return loadProps(propsId);
      if (fixtureName) {
        const map = window.__VALIDITY_FIXTURES__?.[componentPath];
        const props = map?.[fixtureName] as Record<string, unknown> | undefined;
        if (props) return props;
      }
      return {};
    };

    Promise.all([loader(), resolveSingleProps()])
      .then(([mod, props]) => {
        const Component = pickComponentExport(mod, componentPath);
        if (!Component) {
          setState({ kind: 'error', message: 'No exported component in ' + componentPath });
          return;
        }
        // Base props (from propsId / fixture) are stored once. Overrides
        // live in their own state and get merged at render time so a
        // postMessage-driven override change reuses the resolved Component
        // and base props without re-running the loader.
        setState({
          kind: 'ready-single',
          Component,
          baseProps: hydrateProxySentinels(props as Record<string, unknown>) as Record<string, unknown>,
        });
      })
      .catch((err) => setState({ kind: 'error', message: String(err?.message ?? err) }));
  }, []);

  useEffect(() => {
    if (
      state.kind === 'ready-single' ||
      state.kind === 'ready-stacked' ||
      state.kind === 'ready-view' ||
      state.kind === 'ready-index' ||
      state.kind === 'error'
    ) {
      // Perf anchor: stamp time-to-ready (navigation → first usable render)
      // the first time we reach a terminal state. performance.now() is
      // relative to navigation start.
      if (typeof window.__VALIDITY_PERF_READY_MS__ !== 'number') {
        try {
          window.__VALIDITY_PERF_READY_MS__ = performance.now();
        } catch (_) {
          /* no perf clock */
        }
      }
      // signal to Playwright that we are done. Two layers of deferral so
      // initial-effect fetches from the just-mounted component have a chance
      // to register against the interceptor BEFORE Playwright thinks we're
      // ready (which would race the post-ready networkidle wait).
      window.__validityReady = true;
      Promise.resolve().then(() => {
        requestAnimationFrame(() => {
          document.documentElement.setAttribute('data-validity-ready', 'true');
        });
      });
    }
  }, [state.kind]);

  if (state.kind === 'loading') return null;
  if (state.kind === 'error') {
    return (
      <pre
        data-validity-error="true"
        style={{
          padding: 16,
          color: '#b00020',
          font: '13px ui-monospace, Menlo, monospace',
          whiteSpace: 'pre-wrap',
        }}
      >
        Validity render error: {state.message}
      </pre>
    );
  }
  ${
    hasBrowseIndex
      ? `if (state.kind === 'ready-index') {
    return <Index />;
  }`
      : ''
  }

  if (state.kind === 'ready-view') {
    const { results, layout, title, viewName } = state;
    const isGrid = layout === 'grid';
    return (
      <ValidityErrorBoundary source="wrapper">
        <Wrapper colorScheme={colorScheme}>
          <div
            data-validity-view={viewName}
            data-validity-view-layout={layout}
            style={{
              display: 'flex',
              flexDirection: isGrid ? 'row' : 'column',
              flexWrap: isGrid ? 'wrap' : 'nowrap',
              alignItems: isGrid ? 'flex-start' : 'stretch',
              gap: 32,
              padding: 24,
              boxSizing: 'border-box',
              minHeight: '100%',
            }}
          >
            {title ? (
              <header
                data-validity-view-title="true"
                style={{
                  font:
                    '12px/1 ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
                  textTransform: 'uppercase',
                  letterSpacing: '0.08em',
                  color: '#475569',
                  width: '100%',
                }}
              >
                {title}
              </header>
            ) : null}
            {results.map((r, i) => (
              <section
                key={i}
                data-validity-view-item={i}
                data-validity-view-component={r.componentPath}
                style={{
                  display: 'flex',
                  flexDirection: 'column',
                  gap: 8,
                  flex: isGrid ? '0 0 auto' : '0 0 auto',
                }}
              >
                <header
                  style={{
                    font:
                      '11px/1 ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
                    textTransform: 'uppercase',
                    letterSpacing: '0.06em',
                    color: '#64748b',
                  }}
                >
                  {r.label}
                </header>
                <ValidityErrorBoundary source="component">
                  {r.ok ? (
                    <React.Profiler id="validity-render" onRender={__validityOnRender}>
                      <r.Component {...r.props} />
                    </React.Profiler>
                  ) : (
                    <pre
                      data-validity-error="true"
                      style={{
                        margin: 0,
                        padding: 12,
                        color: '#b00020',
                        background: 'rgba(176, 0, 32, 0.06)',
                        border: '1px dashed rgba(176, 0, 32, 0.4)',
                        borderRadius: 6,
                        font:
                          '12px ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
                        whiteSpace: 'pre-wrap',
                      }}
                    >
                      {r.error}
                    </pre>
                  )}
                </ValidityErrorBoundary>
              </section>
            ))}
          </div>
        </Wrapper>
      </ValidityErrorBoundary>
    );
  }

  if (state.kind === 'ready-stacked') {
    const { Component, fixtures } = state;
    return (
      <ValidityErrorBoundary source="wrapper">
        <Wrapper colorScheme={colorScheme}>
          <ValidityErrorBoundary source="component">
            <div
              data-validity-stack="true"
              style={{
                display: 'flex',
                flexDirection: 'column',
                gap: 32,
                padding: 24,
              }}
            >
              {fixtures.map((fx) => (
                <section
                  key={fx.id}
                  data-validity-fixture={fx.id}
                  style={{ display: 'flex', flexDirection: 'column', gap: 8 }}
                >
                  <header
                    style={{
                      font:
                        '11px/1 ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
                      textTransform: 'uppercase',
                      letterSpacing: '0.06em',
                      color: '#64748b',
                    }}
                  >
                    {fx.id}
                  </header>
                  <div>
                    <React.Profiler id="validity-render" onRender={__validityOnRender}>
                      <Component {...fx.props} />
                    </React.Profiler>
                  </div>
                </section>
              ))}
            </div>
          </ValidityErrorBoundary>
        </Wrapper>
      </ValidityErrorBoundary>
    );
  }

  const { Component, baseProps } = state;
  // Merge at render time so postMessage-driven override changes flow into
  // the next render without remounting the Component (and without losing
  // any local component state it accumulated).
  const mergedProps = { ...baseProps, ...overrides };
  return (
    <ValidityErrorBoundary source="wrapper">
      <Wrapper colorScheme={colorScheme}>
        <ValidityErrorBoundary source="component">
          {/* 16px gutter so components don't render flush against the iframe
              edge. Single-render only — stacked / index views have their own
              spacing. min-height lets vertically-centered children still work. */}
          <div
            data-validity-pad="true"
            style={{ padding: 16, boxSizing: 'border-box', minHeight: '100%' }}
          >
            <React.Profiler id="validity-render" onRender={__validityOnRender}>
              <Component {...mergedProps} />
            </React.Profiler>
          </div>
        </ValidityErrorBoundary>
      </Wrapper>
    </ValidityErrorBoundary>
  );
}

const root = document.getElementById('root');
if (root) createRoot(root).render(React.createElement(App));

${inspectorBoot}`,
  );

  return {
    validityDir: dir,
    entryFile: entryFile(projectRoot),
    indexHtml: indexHtml(projectRoot),
    propsDir: propsDir(projectRoot),
    tailwindShim: hasTailwindV4,
  };
}

export function writePropsFile(
  projectRoot: string,
  propsId: string,
  props: Record<string, unknown>,
): void {
  ensureDir(propsDir(projectRoot));
  writeFileSync(resolve(propsDir(projectRoot), `${propsId}.json`), JSON.stringify(props));
}

/**
 * Source of `node_modules/.validity/validity-net-bootstrap.ts`. The one job
 * this module has is to APPLY the fetch + XHR interceptors at module-evaluation
 * time — nothing else in the sandbox does. entry.tsx imports it FIRST, so the
 * patch is live before the user's Wrapper import evaluates its provider graph.
 *
 * The interceptors are applied without any config (which handlers match etc.
 * isn't known until entry.tsx's body runs setupValidityNetwork). So the request
 * listener defers to a mutable `responder` that setupValidityNetwork installs
 * via `wireValidityResponder`; until then it AWAITS a ready-promise, holding —
 * never passing through — any request that fires early. This is the invariant
 * that closes the "request escaped before the mock layer was ready" class of
 * bug: whatever fires (a singleton API client at module-eval, an auth client's
 * get-session on provider mount), the interceptor is already installed and the
 * request is queued until real handlers exist.
 */
const VALIDITY_NET_BOOTSTRAP_SOURCE = `// Generated by @validity.ai/verify-web. Do not edit — recreated per render.
//
// NETWORK INTERCEPTOR BOOTSTRAP. Imported FIRST by the generated entry so its
// body runs before the user's Wrapper (and the whole provider/API/auth-client
// graph the Wrapper statically pulls in). It patches globalThis.fetch and the
// XMLHttpRequest prototype SYNCHRONOUSLY here — @mswjs/interceptors' apply()
// assigns the global before its first await — the only way to guarantee no
// request escapes to the real network in the window between "user module eval"
// and "handlers wired".
//
// Handler wiring needs the per-render config that only entry.tsx's body has, so
// it happens later, in setupValidityNetwork (validity-msw). Until that call
// hands over a responder, the request listener AWAITS a ready-promise:
// @mswjs/interceptors awaits async 'request' listeners before falling through,
// so an early request simply PENDS until the responder exists, then drains
// against the real handlers. It never reaches the network.
//
// Sync XMLHttpRequest is the one category an async listener cannot hold; a sync
// XHR fired before wiring is recorded on window.__VALIDITY_PREREADY__ so
// diagnostics can attribute it rather than let it look like an app console
// error. Sync XHR at module-eval is vanishingly rare in React apps.

import { FetchInterceptor } from '@mswjs/interceptors/fetch';
import { XMLHttpRequestInterceptor } from '@mswjs/interceptors/XMLHttpRequest';

// Sentinel a responder returns to mean "pend this request forever" (the forced
// 'loading' data-state axis). Symbol.for so validity-msw and this module share
// ONE identity across the module boundary.
export const VALIDITY_HANG = Symbol.for('validity.net.hang');

export type ValidityResponder = (
  method: string,
  url: string,
) => Response | typeof VALIDITY_HANG | undefined;

// Installed by setupValidityNetwork once config handlers are known. Null until
// then — the request listener waits on \`ready\` while it is null.
let responder: ValidityResponder | null = null;
let markReady: () => void = () => {};
const ready: Promise<void> = new Promise((resolve) => {
  markReady = resolve;
});

declare global {
  interface Window {
    // Requests that reached the interceptor BEFORE handlers were wired. In the
    // normal async path these were HELD and still served correctly, so the list
    // is a diagnostic (the app fires network at eval/mount, ahead of the mocks).
    // A sync-XHR entry is the only one that represents a genuine escape.
    __VALIDITY_PREREADY__?: string[];
  }
}

function notePreReady(method: string, url: string): void {
  try {
    if (!Array.isArray(window.__VALIDITY_PREREADY__)) window.__VALIDITY_PREREADY__ = [];
    window.__VALIDITY_PREREADY__.push(method + ' ' + url);
  } catch (_) {
    /* diagnostics are best-effort */
  }
}

/**
 * Install the responder and release every request held on \`ready\`. Called once
 * from setupValidityNetwork. Idempotent under HMR: a stale re-evaluation can
 * only re-point the responder and re-resolve an already-resolved promise.
 */
export function wireValidityResponder(fn: ValidityResponder): void {
  responder = fn;
  markReady();
}

async function handleRequest(
  method: string,
  url: string,
  controller: { respondWith: (response: Response) => void },
): Promise<void> {
  if (!responder) {
    notePreReady(method, url);
    // Hold until handlers are wired rather than falling through to the network.
    await ready;
  }
  const result = responder ? responder(method, url) : undefined;
  if (result === VALIDITY_HANG) {
    // Forced 'loading' — pend forever (true delay, no fake timers).
    await new Promise<never>(() => {});
    return;
  }
  if (result instanceof Response) {
    controller.respondWith(result);
  }
  // undefined → leave unhandled so @mswjs/interceptors performs the real
  // request. Only Validity-internal endpoints (/props/, /__validity/) reach
  // this branch (respondTo returns undefined for them); the dev server serves
  // them.
}

// Guard against a double-apply if this module is evaluated twice in one realm.
// apply() is idempotent per interceptor instance, but a second instance proxies
// a second listener onto the running one and double-emits. First eval wins.
const APPLIED = Symbol.for('validity.net.bootstrap.applied');
const g = globalThis as unknown as Record<symbol, unknown>;
if (!g[APPLIED]) {
  g[APPLIED] = true;

  const fetchInterceptor = new FetchInterceptor();
  fetchInterceptor.on('request', async ({ request, controller }) => {
    await handleRequest(request.method, request.url, controller);
  });
  fetchInterceptor.apply();

  const xhrInterceptor = new XMLHttpRequestInterceptor();
  xhrInterceptor.on('request', async ({ request, controller }) => {
    await handleRequest(request.method, request.url, controller);
  });
  xhrInterceptor.apply();
}
`;

/**
 * Source of `node_modules/.validity/validity-msw.ts`. Inlined as a string
 * so prepareSandbox can write it next to entry.tsx — Vite then compiles it
 * the same way it compiles entry.tsx (TypeScript + ESM, no separate build
 * step). Writing it as a generated sibling rather than an in-place template
 * keeps prepare.ts readable and entry.tsx focused on the React mount logic.
 */
const VALIDITY_MSW_SOURCE = `// Generated by @validity.ai/verify-web. Do not edit — recreated per render.
//
// Network HANDLER layer for Validity's isolation sandbox. The interceptors
// themselves (globalThis.fetch + the XMLHttpRequest prototype) are patched
// earlier, at module-eval time, by validity-net-bootstrap — the entry's first
// import — so a fetch fired while the user's Wrapper graph evaluates can't
// escape. This module turns the per-render config (handlers, fallback policy,
// forced data-state axis) into a RESPONDER and hands it to the bootstrap via
// wireValidityResponder(); that both installs the responder and releases any
// request the bootstrap held while handlers were still unknown.

import { wireValidityResponder, VALIDITY_HANG } from './validity-net-bootstrap';

type BodyKind =
  | { json?: unknown; text?: string };

interface Handler extends BodyKind {
  url: string;
  method?: string;
  status?: number;
  headers?: Record<string, string>;
}

type Fallback = 'permissive' | 'populate' | 'reject' | (BodyKind & { status?: number; headers?: Record<string, string> });

interface NetworkPayload {
  fallback: Fallback;
  handlers: Handler[];
  // Scenario-level forced data state (A2) — e.g. a 'server-down' scenario.
  dataState?: string;
}

interface SetupArgs {
  base?: NetworkPayload;
  scenario?: NetworkPayload;
  // Verify-time forced data state (?dataState= URL param). Wins over the
  // scenario-level value; 'populated' normalizes to "no forcing".
  dataState?: string;
}

function pathOf(url: string): string {
  try {
    return new URL(url).pathname;
  } catch {
    // Pattern was a path or invalid URL; treat input as-is.
    return url;
  }
}

function matchUrl(pattern: string, requestUrl: string): boolean {
  // If pattern looks absolute, match the full URL; otherwise match path only.
  const requestSide = /^https?:\\/\\//.test(pattern) ? requestUrl : pathOf(requestUrl);
  if (pattern.endsWith('/*')) {
    const prefix = pattern.slice(0, -1); // includes trailing slash
    return requestSide.startsWith(prefix);
  }
  if (pattern.includes('*')) {
    // Escape regex metacharacters EXCEPT '*' (which we then convert to '.*').
    const re = new RegExp('^' + pattern.replace(/[.+?^$(){}|[\\\\]\\\\]/g, '\\\\$&').replace(/\\*/g, '.*') + '$');
    return re.test(requestSide);
  }
  return requestSide === pattern;
}

function methodMatches(want: string | undefined, actual: string): boolean {
  if (!want || want === '*') return true;
  return want.toUpperCase() === actual.toUpperCase();
}

function buildResponse(handler: BodyKind & { status?: number; headers?: Record<string, string> }): Response {
  const headers = new Headers(handler.headers ?? {});
  const status = handler.status ?? 200;
  if (handler.json !== undefined) {
    if (!headers.has('content-type')) headers.set('content-type', 'application/json');
    return new Response(JSON.stringify(handler.json), { status, headers });
  }
  if (handler.text !== undefined) {
    if (!headers.has('content-type')) headers.set('content-type', 'text/plain; charset=utf-8');
    return new Response(handler.text, { status, headers });
  }
  return new Response('', { status, headers });
}

/**
 * "Permissive" auto-mock body. We default unmatched GETs to a shape that
 * looks plausibly like what the endpoint name suggests — most browse-mode
 * crashes are \`Cannot read properties of undefined (reading 'map')\`
 * coming from list-like endpoints returning the previous default ({}).
 *
 *   - URL path ends in plural ("...s") or has /list/, /search, /feed,
 *     /items, /games, /openings, /messages → []
 *   - Path ends in /count or /stats → { count: 0 }
 *   - Path ends in /state or /status → { status: "ok" }
 *   - Everything else → {}
 *
 * Non-GET (POST/PUT/PATCH/DELETE) defaults to { ok: true } so mutation
 * handlers don't break.
 */
function permissiveBody(method: string, url: string): string {
  if (method.toUpperCase() !== 'GET') return JSON.stringify({ ok: true });
  let path = url;
  try { path = new URL(url, 'http://x').pathname; } catch { /* fall through */ }
  const segments = path.split('/').filter(Boolean).map((s) => s.toLowerCase());
  const last = segments[segments.length - 1] ?? '';
  // Scalar-shape hints win over list hints (count/stats/status are common
  // names but always single-value endpoints).
  if (last === 'count' || /count$/.test(last)) return JSON.stringify({ count: 0 });
  if (last === 'stats' || last === 'metrics' || last === 'summary') {
    return JSON.stringify({ count: 0, total: 0 });
  }
  if (last === 'state' || last === 'status' || last === 'health') {
    return JSON.stringify({ status: 'ok' });
  }
  // List heuristic: ANY segment in the path is list-shaped. Catches both
  // /games (last-segment plural) AND /courses/progress/user (intermediate
  // plural). Tradeoff: a GET that wanted \`{user: {...}}\` may now get \`[]\`,
  // but that's a strictly smaller blast radius than crashing the render on
  // \`.forEach is not a function\`. Users with object-shaped GETs can pin
  // them in .validity/config.ts handlers.
  const listSegments = new Set([
    'list', 'all', 'items', 'results', 'search', 'feed', 'messages',
    'games', 'openings', 'analyses', 'puzzles', 'plans', 'courses',
    'variations', 'challenges', 'events', 'notifications', 'comments',
    'reviews', 'posts', 'orders', 'users', 'products', 'tags', 'categories',
    'projects', 'tasks', 'progress', 'structures',
  ]);
  for (const seg of segments) {
    if (listSegments.has(seg)) return '[]';
  }
  // Plural-noun heuristic on the LAST segment: ends in -s but not in
  // common false positives (-ss / -us / -is / -os / -as) and not a path
  // parameter that happens to look plural.
  if (/^[a-z][a-z0-9_-]+s$/.test(last) && !/(ss|us|is|os|as)$/.test(last)) {
    return '[]';
  }
  return '{}';
}

// Does a URL look like an RSS/Atom feed? Used ONLY under fallback:'populate',
// where an un-mocked feed must answer XML (a JSON []/{} never parses as a feed).
// Kept byte-for-byte in sync with @validity.ai/verify-native's isFeedUrl via the shared
// POPULATED_BODY_CASES table. Self-contained (only globals: URL, String).
function isFeedUrl(url: string): boolean {
  let host = '';
  let path = String(url).toLowerCase();
  try {
    const u = new URL(url, 'http://x');
    host = u.hostname.toLowerCase();
    path = u.pathname.toLowerCase();
  } catch { /* fall through: treat the raw input as the path */ }
  if (/\\.(rss|atom|xml)(\\?|$)/.test(path)) return true;
  if (/(^|\\/)(feed|feeds|rss|atom)(\\/|$)/.test(path)) return true;
  if (/(^|\\.)(feeds?|rss)\\./.test(host)) return true;
  return false;
}

// A minimal but valid RSS 2.0 document with synthetic items, returned for an
// un-mocked feed URL under fallback:'populate'. Kept in sync with native's
// feedBody via the shared cases. Self-contained (only globals: String).
function feedBody(url: string): string {
  const esc = (s: string): string =>
    String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const titles = ['The First Episode', 'Building in Public', 'Lessons From the Field', 'A Deep Dive', 'Looking Ahead'];
  const dates = ['Mon, 01 Jan 2024 12:00:00 GMT', 'Mon, 08 Jan 2024 12:00:00 GMT', 'Mon, 15 Jan 2024 12:00:00 GMT', 'Mon, 22 Jan 2024 12:00:00 GMT', 'Mon, 29 Jan 2024 12:00:00 GMT'];
  let items = '';
  for (let i = 0; i < 5; i++) {
    items += '<item>' + '<title>' + esc(titles[i % 5]) + '</title>' + '<link>https://example.com/episode/' + (i + 1) + '</link>' + '<guid>episode-' + (i + 1) + '</guid>' + '<pubDate>' + dates[i % 5] + '</pubDate>' + '<description>A synthetic episode generated by Validity for isolated rendering.</description>' + '<enclosure url="https://example.com/episode/' + (i + 1) + '.mp3" type="audio/mpeg" length="0"/>' + '</item>';
  }
  return '<?xml version="1.0" encoding="UTF-8"?>' + '<rss version="2.0"><channel>' + '<title>Validity Sample Feed</title>' + '<link>' + esc(url) + '</link>' + '<description>Synthetic feed for isolated rendering</description>' + items + '</channel></rss>';
}

// "Populate" auto-mock body (opt-in fallback:'populate'): unlike permissiveBody
// (empty shapes), returns synthetic POPULATED data so list/detail screens render
// content. Kept in sync with native's populatedBody via the shared cases.
// Self-contained (only globals: URL, JSON, String).
function populatedBody(method: string, url: string): string {
  if (String(method).toUpperCase() !== 'GET') return JSON.stringify({ ok: true });
  const item = (i: number) => {
    const titles = ['Welcome back', 'Project overview', 'Latest updates', 'Quick stats', 'Recent activity'];
    const names = ['Jane Doe', 'Alice Carter', 'Bob Singh', 'Yuki Tanaka', 'Marcus Chen'];
    return {
      id: 'id-' + (1000 + i),
      title: titles[i % 5],
      name: names[i % 5],
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      imageUrl: 'https://picsum.photos/seed/' + (i + 1) + '/400/300',
      url: 'https://example.com/item/' + (i + 1),
      publishedAt: '2024-01-' + String((i % 28) + 1).padStart(2, '0') + 'T12:00:00.000Z',
    };
  };
  let path = String(url);
  try { path = new URL(url, 'http://x').pathname; } catch { /* fall through */ }
  const segments = path.split('/').filter(Boolean).map((s) => s.toLowerCase());
  const last = segments[segments.length - 1] ?? '';
  if (last === 'count' || /count$/.test(last)) return JSON.stringify({ count: 3 });
  if (last === 'stats' || last === 'metrics' || last === 'summary') return JSON.stringify({ count: 3, total: 3 });
  if (last === 'state' || last === 'status' || last === 'health') return JSON.stringify({ status: 'ok' });
  const listSegments = new Set(['list', 'all', 'items', 'results', 'search', 'feed', 'messages', 'games', 'openings', 'analyses', 'puzzles', 'plans', 'courses', 'variations', 'challenges', 'events', 'notifications', 'comments', 'reviews', 'posts', 'orders', 'users', 'products', 'tags', 'categories', 'projects', 'tasks', 'progress', 'structures', 'episodes', 'articles', 'stories']);
  const isList = segments.some((s) => listSegments.has(s)) || (/^[a-z][a-z0-9_-]+s$/.test(last) && !/(ss|us|is|os|as)$/.test(last));
  if (isList) {
    const arr = [];
    for (let i = 0; i < 5; i++) arr.push(item(i));
    return JSON.stringify(arr);
  }
  return JSON.stringify(item(0));
}

function fallbackResponse(
  fallback: Fallback,
  method: string,
  url: string,
): Response {
  if (fallback === 'permissive') {
    return new Response(permissiveBody(method, url), {
      status: 200,
      headers: { 'content-type': 'application/json' },
    });
  }
  if (fallback === 'populate') {
    // POPULATE (default): list + feed URLs answer real synthetic data so those
    // screens render content (untagged → .json()/.text() yield the body). Feeds
    // answer XML; list-ish URLs a populated array.
    if (isFeedUrl(url)) {
      return new Response(feedBody(url), {
        status: 200,
        headers: { 'content-type': 'application/xml' },
      });
    }
    const pb = populatedBody(method, url);
    if (pb.charAt(0) === '[') {
      return new Response(pb, {
        status: 200,
        headers: { 'content-type': 'application/json' },
      });
    }
    // Singular / scalar / non-GET keep the EXACT crash-safe permissive
    // guarantee: the shape-heuristic body, tagged here (the call site only tags
    // the 'permissive' policy) so the shimmed Response.json returns the
    // deep-default Proxy and destructuring an un-mocked field can't throw.
    const res = new Response(permissiveBody(method, url), {
      status: 200,
      headers: { 'content-type': 'application/json' },
    });
    res.headers.set('x-validity-permissive', '1');
    return res;
  }
  if (fallback === 'reject') {
    return new Response('Validity: no handler matched', { status: 599 });
  }
  return buildResponse(fallback);
}

function combine(base: NetworkPayload | undefined, scenario: NetworkPayload | undefined): {
  fallback: Fallback;
  handlers: Handler[];
} {
  const baseHandlers = base?.handlers ?? [];
  const scenarioHandlers = scenario?.handlers ?? [];
  return {
    // scenario fallback wins if set; DEFAULT 'populate' (see browserNetworkPayload).
    fallback: scenario?.fallback ?? base?.fallback ?? 'populate',
    // scenario handlers tried first → win on URL conflict
    handlers: [...scenarioHandlers, ...baseHandlers],
  };
}

// One intercepted request (matched handler OR fallback). \`provenance\` is the
// load-bearing signal: 'declared' requires the positive conjunction "a config
// handler matched AND the body is not the fabricated proxy" — every ambiguity
// resolves to 'fabricated'. \`handlerUrl\` names the config handler pattern that
// served a declared response so the verdict can cite it.
type ValidityRequestEntry = {
  method: string;
  url: string;
  status: number;
  matched: boolean;
  permissive: boolean;
  provenance: 'declared' | 'fabricated';
  handlerUrl?: string;
  // Set when the response was FORCED by the dataState axis (A2) — the
  // x-validity-datastate header, or 'loading' for a hung request. The seam
  // A3 reads to tell intentional synthetic data from accidental fabrication.
  dataState?: string;
};

declare global {
  interface Window {
    __VALIDITY_UNMATCHED__?: string[];
    // Structured mirror of __VALIDITY_UNMATCHED__: each unmatched request plus
    // the fabricated body the fallback answered (parsed JSON when it parsed,
    // else the raw string, truncated), so diagnostics can emit a paste-ready
    // config handler stub. Body is filled asynchronously (a clone read), so an
    // entry may briefly lack it — capture reads well after the render settles.
    __VALIDITY_UNMATCHED_REQUESTS__?: Array<{ method: string; url: string; body?: unknown }>;
    // Every intercepted request (matched handler OR fallback), recorded so
    // the deterministic hard-check executor can assert \`expect.network\` in
    // ISOLATION mode — where @mswjs/interceptors serves the response inside
    // the page's JS realm and Playwright's page.on('response') never fires.
    // MIRROR of the canonical closure log (kept for old executors +
    // diagnostics) — component code can mutate it, so verdicts never read it
    // when the getter below is available.
    __VALIDITY_REQUESTS__?: ValidityRequestEntry[];
    // TAMPER-PROOF reader for the canonical request log: a frozen closure
    // getter (non-writable, non-configurable) returning copies of the entries.
    // Defined during this module's evaluation — BEFORE any user component code
    // runs (entry.tsx top-level awaits setupValidityNetwork ahead of the
    // dynamic component import) — so component code can neither pre-define nor
    // reassign it, and pushing forged entries into the mirror array above is
    // inert for verdicts.
    __VALIDITY_GET_REQUESTS__?: () => ValidityRequestEntry[];
  }
}

function trackUnmatched(url: string): void {
  if (!Array.isArray(window.__VALIDITY_UNMATCHED__)) {
    window.__VALIDITY_UNMATCHED__ = [];
  }
  window.__VALIDITY_UNMATCHED__.push(url);
}

// Structured record of an unmatched request + the body the fallback fabricated
// for it (paste-ready-stub source). The entry is pushed synchronously so counts
// stay deterministic; \`body\` is filled from a clone read (\`.text()\` is
// unpatched — only \`.json()\` returns the deep-default Proxy — so this reads the
// real body). Best-effort: a clone/parse failure just leaves \`body\` undefined.
function trackUnmatchedRequest(method: string, url: string, response: Response): void {
  if (!Array.isArray(window.__VALIDITY_UNMATCHED_REQUESTS__)) {
    window.__VALIDITY_UNMATCHED_REQUESTS__ = [];
  }
  const entry: { method: string; url: string; body?: unknown } = { method, url };
  window.__VALIDITY_UNMATCHED_REQUESTS__.push(entry);
  try {
    response
      .clone()
      .text()
      .then((raw) => {
        let text = String(raw);
        if (text.length > 2000) text = text.slice(0, 2000);
        try { entry.body = JSON.parse(text); } catch { entry.body = text; }
      })
      .catch(() => { /* body unreadable — leave undefined */ });
  } catch { /* clone failed — leave undefined */ }
}

// CANONICAL request log — a closure array only trackRequest can append to.
// The executor reads it through the frozen \`__VALIDITY_GET_REQUESTS__\` getter,
// so component code (which the agent writes, in the same JS realm) cannot
// forge a \`provenance: 'declared'\` entry by pushing into the window mirror.
// First definition wins: this module evaluates before any user code, and an
// HMR re-evaluation keeps the existing getter (its closure array goes stale,
// which fails SAFE — the executor then sees fewer entries, never forged ones).
const __validityRequestLog: ValidityRequestEntry[] = [];
try {
  if (!Object.prototype.hasOwnProperty.call(window, '__VALIDITY_GET_REQUESTS__')) {
    Object.defineProperty(window, '__VALIDITY_GET_REQUESTS__', {
      value: () => __validityRequestLog.map((e) => ({ ...e })),
      writable: false,
      configurable: false,
      enumerable: false,
    });
  }
} catch (_) {
  /* already defined and frozen — keep the first */
}

// \`permissive\` records that the response carried the x-validity-permissive
// header — i.e. its body is the deeply-defaulting Proxy (fabricated data), not
// anything the component actually fetched. The hard-check executor reads this
// to TAINT any \`expect.network\` assertion that consumed a fabricated response,
// demoting an otherwise-passing criterion to unverifiable. The header is set in
// exactly two places (the 'permissive' fallback at respondTo, and the populate
// fallback's scalar/non-GET branch in fallbackResponse), so \`permissive\` is a
// faithful, non-leaky signal. \`provenance\` folds both signals into the
// declared-vs-fabricated label (see ValidityRequestEntry); \`handlerUrl\` is
// passed ONLY from respondTo's handler-match branch.
function trackRequest(
  method: string,
  url: string,
  response: Response,
  matched: boolean,
  handlerUrl?: string,
): void {
  if (!Array.isArray(window.__VALIDITY_REQUESTS__)) {
    window.__VALIDITY_REQUESTS__ = [];
  }
  const permissive = response.headers.get('x-validity-permissive') === '1';
  const entry: ValidityRequestEntry = {
    method,
    url,
    status: response.status,
    matched,
    permissive,
    provenance: matched && !permissive ? 'declared' : 'fabricated',
  };
  if (handlerUrl !== undefined) entry.handlerUrl = handlerUrl;
  const forcedState = response.headers.get('x-validity-datastate');
  if (forcedState) entry.dataState = forcedState;
  __validityRequestLog.push(entry);
  window.__VALIDITY_REQUESTS__.push({ ...entry });
}

// Log a request the dataState axis HUNG (forced 'loading'): there is no
// Response object, so the evidence is written first, then the listener awaits
// forever. status 0 = never answered; always fabricated for provenance.
function trackForced(method: string, url: string, status: number, dataState: string): void {
  if (!Array.isArray(window.__VALIDITY_REQUESTS__)) {
    window.__VALIDITY_REQUESTS__ = [];
  }
  const entry: ValidityRequestEntry = {
    method,
    url,
    status,
    matched: false,
    permissive: false,
    provenance: 'fabricated',
    dataState,
  };
  __validityRequestLog.push(entry);
  window.__VALIDITY_REQUESTS__.push({ ...entry });
}

/**
 * Same-origin paths Validity owns and MUST NOT intercept. The sandbox's
 * own entry.tsx fetches \`/props/<id>.json\` to load fixture props; the
 * browse-mode index fetches \`/__validity/api/config\` (and friends) from
 * Vite middlewares registered in server.ts. If either request is captured
 * by the FetchInterceptor it falls through to the permissive fallback
 * (200 + {}), and the caller silently sees an empty response — the
 * component mounts with no props, or the browse sidebar shows "no
 * components." Keep this list in sync with the routes registered in
 * registerValidityMiddlewares (packages/verify-web/src/server.ts) and any
 * internal endpoints added under /props/ in entry.tsx.
 */
const VALIDITY_INTERNAL_PATH_PREFIXES = ['/props/', '/__validity/'];

function isValidityInternalUrl(url: string): boolean {
  let path = url;
  try {
    const parsed = new URL(url, window.location.origin);
    if (parsed.origin !== window.location.origin) return false;
    path = parsed.pathname;
  } catch {
    // Relative or malformed — fall through to prefix check on the raw string.
  }
  for (const prefix of VALIDITY_INTERNAL_PATH_PREFIXES) {
    if (path.startsWith(prefix)) return true;
  }
  return false;
}

/**
 * Build a deeply-defaulting Proxy that satisfies essentially any
 * property access without crashing.
 *
 *   .foo                    → another proxy
 *   .length                 → 0
 *   .map / .filter / .find  → returns [] / undefined
 *   .forEach                → no-op
 *   .reduce(fn, init)       → init
 *   .toFixed(n)             → "0"
 *   .toLocaleString()       → "0"
 *   for-of iteration        → yields nothing
 *   String(p)               → ""
 *   Number(p) / +p          → 0
 *   p == null               → true (so \`data ?? fallback\` picks fallback)
 *
 * Used as the permissive fallback's deserialized form so a component
 * calling \`progressData.partialResults.length\` against an un-mocked
 * endpoint just sees 0 instead of crashing with "Cannot read properties
 * of undefined". Validity logs the unmatched URL so the user can pin it
 * down in .validity/config.ts, but the render stays alive.
 */
function makeDeepDefaultProxy(callable = false): unknown {
  // The TOP-level proxy uses an object target so \`typeof data === 'object'\`
  // (matches parsed JSON) and React doesn't trip its "Functions are not
  // valid as a React child" check on \`{data.someField}\`.
  //
  // CHILD proxies (\`data.foo\`) use a function target so arbitrary method
  // calls like \`data.foo.someUnknownMethod()\` don't throw. Consumers
  // sometimes render \`{data.foo}\` directly — React still tolerates that
  // because the displayed value is a function (which React skips) rather
  // than a React-element-shaped object (which would throw).
  const recurse = () => makeDeepDefaultProxy(true);
  const target: Record<string | symbol, unknown> = callable
    ? (function shim() { return recurse(); } as unknown as Record<string | symbol, unknown>)
    : {};
  return new Proxy(target, {
    get(target, prop) {
      const desc = Reflect.getOwnPropertyDescriptor(target, prop);
      if (desc && desc.configurable === false && 'value' in desc) return desc.value;
      // Primitive coercion hooks — make conversion to string/number sane.
      if (prop === Symbol.toPrimitive) {
        return (hint: string) => (hint === 'number' ? 0 : hint === 'string' ? '' : 0);
      }
      if (prop === 'toString') return () => '';
      if (prop === 'valueOf') return () => 0;
      if (prop === Symbol.iterator) return function* () {};
      if (prop === Symbol.asyncIterator) return async function* () {};
      // Skip the thenable detection — returning a function here would make
      // \`await proxy\` think it's a Promise.
      if (prop === 'then') return undefined;
      // React's plain-object check inspects $$typeof; return undefined so
      // React doesn't think the proxy is an element / portal / etc.
      if (typeof prop === 'symbol') return undefined;
      // Collection-shape: empty length / no items.
      if (prop === 'length' || prop === 'size') return 0;
      if (prop === 'map' || prop === 'filter') return () => [];
      if (prop === 'reduce' || prop === 'reduceRight') return (_fn: unknown, init: unknown) => init;
      if (prop === 'forEach' || prop === 'flat' || prop === 'flatMap') return () => [];
      if (prop === 'every') return () => true;
      if (prop === 'some') return () => false;
      if (prop === 'find' || prop === 'findIndex' || prop === 'findLast') {
        return () => (prop === 'findIndex' ? -1 : undefined);
      }
      if (prop === 'includes' || prop === 'indexOf') {
        return () => (prop === 'includes' ? false : -1);
      }
      if (prop === 'join') return () => '';
      if (prop === 'concat' || prop === 'slice' || prop === 'splice') return () => [];
      // Number-shape format methods.
      if (prop === 'toFixed' || prop === 'toPrecision' || prop === 'toExponential') return () => '0';
      if (prop === 'toLocaleString') return () => '0';
      // Name-shape defaults — match common conventions so flag-style
      // checks like \`if (data.isError)\` don't accidentally render the
      // error branch.
      if (typeof prop === 'string') {
        const lower = prop.toLowerCase();
        // is*, has*, can*, should*, did*, was* → boolean false
        if (/^(is|has|can|should|did|was|will|are)[A-Z_]/.test(prop)) return false;
        if (/^loading$|^pending$|^error$|^errored$|^disabled$|^success$/.test(lower)) return false;
        // count / total / *count → number 0
        if (lower === 'count' || lower === 'total' || lower === 'index' || /count$/.test(lower)) return 0;
        // Verb-prefixed method names (fetchEpisodes, getUsers, toggleFavorites)
        // also END in 's' but are FUNCTIONS, not plural nouns — fall through to a
        // callable proxy so calling them no-ops instead of "X is not a function".
        // (A callable proxy still satisfies .map()->[], .length->0.) Must precede
        // the plural-noun rule below, which would otherwise return [].
        if (/^(get|set|fetch|load|create|update|delete|remove|add|submit|save|handle|toggle|clear|reset|select|find|refresh|open|close|on)[A-Z]/.test(prop)) return recurse();
        // Plural noun (likely array) → []
        if (/^[a-z][a-z0-9_]+s$/i.test(prop) && !/(ss|us|is|os|as)$/.test(lower)) return [];
      }
      // Numeric index access (\`proxy[0]\`) — recurse so chained access works.
      return recurse();
    },
    has(target, prop) { return Reflect.has(target, prop); },
    ownKeys(target) { return Reflect.ownKeys(target); },
    getOwnPropertyDescriptor(target, prop) {
      return Reflect.getOwnPropertyDescriptor(target, prop);
    },
  });
}

declare global {
  interface Window {
    __VALIDITY_DEEP_DEFAULT__?: () => unknown;
  }
}
// Expose the proxy factory so the shimmed Response.json can call it.
window.__VALIDITY_DEEP_DEFAULT__ = makeDeepDefaultProxy;

/**
 * Shim \`Response.prototype.json()\` so any Response we tagged with the
 * \`x-validity-permissive\` header resolves to a deeply-defaulting Proxy
 * instead of the parsed (and typically too-empty) JSON body. Untagged
 * responses (real handlers, real network) pass through to the original.
 *
 * Only patches once per page — guarded with a Symbol so HMR reloads
 * don't stack patches.
 */
const VALIDITY_JSON_PATCH = Symbol.for('validity.responseJsonPatched');
function shimResponseJson(): void {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const proto = Response.prototype as any;
  if (proto[VALIDITY_JSON_PATCH]) return;
  const original = proto.json;
  proto.json = async function patchedJson(this: Response) {
    if (this.headers.get('x-validity-permissive') === '1') {
      return makeDeepDefaultProxy();
    }
    return original.call(this);
  };
  proto[VALIDITY_JSON_PATCH] = true;
}

export async function setupValidityNetwork(args: SetupArgs): Promise<void> {
  const { fallback, handlers } = combine(args.base, args.scenario);
  // Forced data-state axis (A2). The verify-time ?dataState= param wins over a
  // scenario-level dataState; 'populated' normalizes to undefined = today's
  // pipeline untouched. Forcing precedes handler matching below — declared
  // handlers are intentionally overridden (the axis asks "what does this UI do
  // when the data layer is in state S", not "what did the user mock").
  const forcedRaw = args.dataState ?? args.scenario?.dataState;
  const forced = forcedRaw === 'populated' ? undefined : forcedRaw;
  shimResponseJson();

  const respondTo = (method: string, url: string): Response | typeof VALIDITY_HANG | undefined => {
    // Pass through Validity-internal endpoints. Returning \`undefined\`
    // lets the @mswjs/interceptors layer fall back to the real network
    // — which here means Vite's dev server serving the static file.
    // Forcing must never break the sandbox's own plumbing, so this stays
    // FIRST, ahead of the forced branches.
    if (isValidityInternalUrl(url)) return undefined;
    if (forced === 'loading') {
      trackForced(method, url, 0, 'loading'); // evidence first — then hang
      return VALIDITY_HANG;
    }
    if (forced === 'error') {
      const res = new Response(JSON.stringify({ error: 'Validity forced error state' }), {
        status: 500,
        headers: { 'content-type': 'application/json', 'x-validity-datastate': 'error' },
      });
      // matched:false → the executor's expect.network taint path stays intact:
      // a status assertion against a response Validity fabricated can never
      // read as proof, whatever the intent.
      trackRequest(method, url, res, false);
      return res;
    }
    if (forced === 'empty') {
      // Permissive-tagged empty body: .json() resolves to the deep-default
      // Proxy, i.e. "populated pipeline with zero items" — crash-safe on
      // singular endpoints and already tainted for expect.network purposes.
      const res = new Response(permissiveBody(method, url), {
        status: 200,
        headers: { 'content-type': 'application/json' },
      });
      res.headers.set('x-validity-permissive', '1');
      res.headers.set('x-validity-datastate', 'empty');
      trackRequest(method, url, res, false);
      return res;
    }
    for (const h of handlers) {
      if (!methodMatches(h.method, method)) continue;
      if (matchUrl(h.url, url)) {
        const res = buildResponse(h);
        // \`h.url\` is the config handler pattern that served this — stamped so
        // a declared verdict can cite it (and the executor can demote a
        // catch-all pattern to fabricated).
        trackRequest(method, url, res, true, h.url);
        return res;
      }
    }
    trackUnmatched(method + ' ' + url);
    const res = fallbackResponse(fallback, method, url);
    // Tag the permissive fallback so the shimmed Response.json knows to
    // return the deeply-defaulting Proxy. Real text-body fallbacks fall
    // through to the original Response.json (just JSON.parse the body).
    if (fallback === 'permissive') res.headers.set('x-validity-permissive', '1');
    trackRequest(method, url, res, false);
    // Record the fabricated body so diagnostics can offer a paste-ready stub.
    trackUnmatchedRequest(method, url, res);
    return res;
  };

  // Hand the responder to the bootstrap. This installs it on the already-applied
  // fetch + XHR interceptors AND resolves the ready-promise, so any request the
  // bootstrap held (fired before handlers were known) now drains against these
  // handlers. respondTo returns VALIDITY_HANG for the forced 'loading' axis; the
  // bootstrap's request listener turns that into a never-resolving promise so
  // the request pends forever. Nothing reached the real network in between.
  wireValidityResponder(respondTo);
}
`;

/**
 * Static HTML shell shared by both sandbox prepare paths (Vite/web and
 * Expo Web). The mount point (`<div id="root">`) is the same target for
 * React 18's `createRoot()` AND react-native-web's
 * `AppRegistry.runApplication({ rootTag: document.getElementById('root') })`.
 *
 * The early-error trap and the scenario-seed script are framework-agnostic
 * — they only depend on `window.fetch` and the DOM, both present in
 * either toolchain.
 */
const INDEX_HTML_SOURCE = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Validity Sandbox</title>
    <script>
      (function () {
        function show(label, message) {
          var pre = document.createElement('pre');
          pre.setAttribute('data-validity-error', 'true');
          pre.style.cssText = 'padding:16px;color:#b00020;font:13px ui-monospace,Menlo,monospace;white-space:pre-wrap;';
          pre.textContent = 'Validity sandbox ' + label + ': ' + message;
          (document.body || document.documentElement).appendChild(pre);
        }
        window.addEventListener('error', function (e) {
          if (document.querySelector('[data-validity-error="true"]')) return;
          show('error', (e.error && (e.error.stack || e.error.message)) || e.message || String(e));
        });
        window.addEventListener('unhandledrejection', function (e) {
          if (document.querySelector('[data-validity-error="true"]')) return;
          show('unhandledRejection', (e.reason && (e.reason.stack || e.reason.message)) || String(e.reason));
        });
      })();
    </script>
    <script>
      // Browse-mode pre-React seed for auth-gated UI.
      //
      // Verify mode uses Playwright's addCookies + addInitScript to plant
      // session state BEFORE any page script runs. Browse mode has no
      // Playwright — so when the URL carries ?scenario=<id>, we fetch the
      // scenario's cookies + storage from a Vite middleware
      // (/__validity/api/scenario-state) and write them ourselves before
      // the React entry module loads. The entry tag is added dynamically
      // AFTER seeding completes so React's first render sees the seeded
      // state.
      //
      // If no ?scenario= is present we mount immediately — keeps verify
      // and the index-page path free of this branch.
      (function () {
        var params = new URLSearchParams(window.location.search);
        var scenario = params.get('scenario');
        function mount() {
          var s = document.createElement('script');
          s.type = 'module';
          s.src = '/entry.tsx';
          // The seed script runs in <head>, so <body> may not exist yet.
          // Append to whichever exists — both end up loading the module
          // the same way.
          (document.body || document.head || document.documentElement).appendChild(s);
        }
        if (!scenario) { mount(); return; }
        fetch('/__validity/api/scenario-state?name=' + encodeURIComponent(scenario))
          .then(function (r) { return r.ok ? r.json() : { cookies: {}, localStorage: {}, sessionStorage: {} }; })
          .then(function (state) {
            try {
              var cookies = state.cookies || {};
              for (var k in cookies) {
                if (Object.prototype.hasOwnProperty.call(cookies, k)) {
                  document.cookie = k + '=' + cookies[k] + '; path=/';
                }
              }
              var ls = state.localStorage || {};
              for (var lk in ls) {
                if (Object.prototype.hasOwnProperty.call(ls, lk)) {
                  try { window.localStorage.setItem(lk, ls[lk]); } catch (e) {}
                }
              }
              var ss = state.sessionStorage || {};
              for (var sk in ss) {
                if (Object.prototype.hasOwnProperty.call(ss, sk)) {
                  try { window.sessionStorage.setItem(sk, ss[sk]); } catch (e) {}
                }
              }
            } catch (e) { /* seeding is best-effort */ }
          })
          .catch(function () { /* middleware absent (verify mode) — fall through and mount */ })
          .finally(mount);
      })();
    </script>
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>
`;
